import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { resolveHiConfigWithReport } from '../dist/config/resolver.js'
import { resolveModel } from '../dist/runtime/routing/model-resolver.js'
import { MissionStore } from '../dist/runtime/mission/mission-store.js'
import { normalizeWorkerResult } from '../dist/runtime/task/contracts.js'
import { startAssessedMission } from './helpers/semantic.mjs'
import { evaluateShellCommand } from '../dist/runtime/process/shell-policy.js'
import { capabilityProfile } from '../dist/runtime/capabilities/profiles.js'
import { ProcessGovernor } from '../dist/runtime/process/governor.js'
import { WorktreeRuntime } from '../dist/runtime/isolation/worktree-runtime.js'
import { readSkillResource } from '../dist/runtime/skills/registry.js'

const baseConfig=()=>resolveHiConfigWithReport({},undefined).config
const models=[{id:'cheap/model',provider:'cheap',cost:1,quality:5,writeCapable:true},{id:'strong/model',provider:'strong',cost:3,quality:9,writeCapable:true}]

test('project topology override reaches mission topology decision',()=>{const root=mkdtempSync(join(tmpdir(),'hi-config-'));try{mkdirSync(join(root,'.opencode','hi','policy'),{recursive:true});writeFileSync(join(root,'.opencode','hi','policy','routing.json'),JSON.stringify({schema:1,type:'hi-routing',execution:{topology:'multi-agent',maxAgents:3,parallelism:2}}));let cfg=resolveHiConfigWithReport({},root).config;const store=new MissionStore(root,{},()=>cfg.primaryMode,()=>({mode:cfg.execution.topology,maxAgents:cfg.execution.maxAgents,parallelism:cfg.execution.parallelism}));assert.equal(startAssessedMission(store,'s','opaque local change',{task_kind:'implementation',scope:'local',required_capabilities:['implementation']}).topology.mode,'multi-agent')}finally{rmSync(root,{recursive:true,force:true})}})
test('explicit task model overrides project fixed model and project fixed overrides adaptive scoring',()=>{const c=baseConfig();c.models={mode:'fixed',default:'cheap/model',roles:{}};assert.equal(resolveModel('deep',models,c,undefined,'coder').primary,'cheap/model');assert.equal(resolveModel('deep',models,c,'strong/model','coder').primary,'strong/model')})
test('project facts do not become methodology observations without the structured reusable-HOW contract',()=>{const fact=normalizeWorkerResult({status:'DONE',summary:'The project uses ResultEnvelope for API errors',changed_files:[],evidence:[],open_issues:[],needs_context:[]});assert.equal(fact.methodology_observations,undefined);const structured=normalizeWorkerResult({status:'DONE',summary:'Reusable project procedure observed',changed_files:[],evidence:[{kind:'review-evidence',summary:'bounded proof',pass:true,outcome:'passed'}],open_issues:[],needs_context:[],methodology_observations:[{key:'project-review-flow',procedure:'Inspect the project-specific review manifest before changing adapters.',trigger:'Adapter review touches the manifest.',do_not_trigger:'No adapter review is involved.',exit_condition:'Manifest constraints are reconciled.',evidence:['review-evidence']}]});assert.equal(structured.methodology_observations?.length,1)})
test('shell policy is non-interactive and never fakes approval',()=>{assert.equal(evaluateShellCommand('npm init').decision,'REWRITE');assert.equal(evaluateShellCommand('gh auth login').decision,'USER_ACTION_REQUIRED');assert.equal(evaluateShellCommand('yes | dangerous-command').decision,'DENY');assert.equal(evaluateShellCommand('npm test').decision,'ALLOW')})
test('capability profiles never expand release authority implicitly',()=>{const release=capabilityProfile('RELEASE'),research=capabilityProfile('RESEARCH'),sandbox=capabilityProfile('SANDBOX');assert.equal(release.externalSideEffects,true);assert.equal(release.requiresAuthority,true);assert.equal(research.write,false);assert.equal(sandbox.requiresIsolation,true)})
test('process governor exposes lifecycle and mission cleanup',()=>{const g=new ProcessGovernor();const state=g.start(process.execPath,['-e','setInterval(()=>{},1000)'],{ownerTask:'t1',purpose:'watcher',cwd:process.cwd()});assert.equal(g.get(state.processId).status,'running');assert.deepEqual(g.cleanupMission(),[state.processId]);assert.equal(g.get(state.processId).status,'stopped')})
test('worktree runtime creates standard git isolation and cleans it up',()=>{const root=mkdtempSync(join(tmpdir(),'hi-wt-repo-')),wtRoot=mkdtempSync(join(tmpdir(),'hi-wt-out-'));try{assert.equal(spawnSync('git',['init','-q'],{cwd:root}).status,0);spawnSync('git',['config','user.email','hi@example.invalid'],{cwd:root});spawnSync('git',['config','user.name','Hi Test'],{cwd:root});writeFileSync(join(root,'a.txt'),'a');spawnSync('git',['add','a.txt'],{cwd:root});assert.equal(spawnSync('git',['commit','-qm','init'],{cwd:root}).status,0);const w=new WorktreeRuntime(root,wtRoot),created=w.create('hi/test-isolation');assert.equal(created.status,'active');assert.equal(w.remove('hi/test-isolation'),true);assert.equal(w.get('hi/test-isolation').status,'removed');assert.throws(()=>w.create('../escape'))}finally{rmSync(root,{recursive:true,force:true});rmSync(wtRoot,{recursive:true,force:true})}})
test('skill resource API rejects traversal',()=>{const root=mkdtempSync(join(tmpdir(),'hi-skill-'));try{const skill=join(root,'skills','hi-example');mkdirSync(join(skill,'references'),{recursive:true});writeFileSync(join(skill,'SKILL.md'),'---\nname: hi-example\n---\n');writeFileSync(join(skill,'references','guide.md'),'guide');const candidate={name:'hi-example',provider:'project',path:join(skill,'SKILL.md'),valid:true,enabled:true,orchestrationRisk:false};assert.equal(readSkillResource(candidate,'references','guide.md'),'guide');assert.throws(()=>readSkillResource(candidate,'references','../secret'))}finally{rmSync(root,{recursive:true,force:true})}})
