import { mkdtempSync,existsSync,readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'
import { decideAdaptiveExecution } from '../dist/runtime/execution/adaptive-policy.js'
import { decideTopology } from '../dist/runtime/execution/topology-policy.js'
import { extractTypeScriptSemanticContext } from '../dist/runtime/semantic/typescript-context.js'
import { redactProviderContext,containsPlaintextSecret,restoreLocalText } from '../dist/runtime/privacy/boundary.js'
import { parseSemanticIntentAssessment } from '../dist/runtime/intent/semantic-assessment.js'
import { startAssessedMission } from './helpers/semantic.mjs'
import { materiallyDifferentRetry } from '../dist/runtime/budget/mission-budget.js'
import { ContextArtifactStore } from '../dist/runtime/context/artifact-store.js'
import { resolveHostCapability,OPENCODE_REFERENCE_CAPABILITIES } from '../dist/runtime/host/capability-manifest.js'
import { deriveEfficiencyMetrics } from '../dist/runtime/telemetry/execution.js'
import { MissionStore } from '../dist/runtime/mission/mission-store.js'
import { durableArtifactPath,projectSkillRoot } from '../dist/runtime/storage/ownership.js'

const intent=(overrides={})=>({objective:'update src/a.ts',taskKind:'implementation',scope:'local',risk:'low',ambiguity:'none',dependencyClass:'independent',requiredCapabilities:['implementation'],likelyVerification:['changed-surface-sanity'],avoid:[],...overrides})

test('direct path is minimum-sufficient by default',()=>{const d=decideAdaptiveExecution(intent());assert.equal(d.path,'DIRECT');assert.ok(d.reasons.some(x=>x.includes('clear reversible scope')))})
test('evidence, planned and escalated paths remain distinct',()=>{assert.equal(decideAdaptiveExecution(intent({ambiguity:'resolvable'})).path,'EVIDENCE');assert.equal(decideAdaptiveExecution(intent({scope:'multi-file',dependencyClass:'sequential'})).path,'PLANNED');assert.equal(decideAdaptiveExecution(intent({risk:'high'})).path,'ESCALATED')})
test('adaptive topology does not fan out without material benefit',()=>{assert.equal(decideTopology(intent()).mode,'single-agent');const multi=decideTopology(intent({scope:'multi-stream',dependencyClass:'independent-multi',requiredCapabilities:['implementation','multi-stream-delegation']}));assert.equal(multi.mode,'multi-agent');assert.ok(multi.agentCount>=2)})
test('explicit topology override has executable precedence',()=>{const multi=decideTopology(intent(),{mode:'multi-agent',maxAgents:4,parallelism:2});assert.equal(multi.mode,'multi-agent');assert.equal(multi.executionMode,'parallel');const single=decideTopology(intent({scope:'multi-stream'}),{mode:'single-agent',maxAgents:4,parallelism:2});assert.equal(single.mode,'single-agent');assert.equal(single.executionMode,'single')})
test('typescript semantic context supplies requested contract without dependency graph',()=>{const source=`import x from 'x'\nconst privateThing=1\nexport interface User { id:string; name:string }\nexport type UserId = string\nexport function loadUser(id:UserId):Promise<User> { throw 0 }\n`+`const noise='${'z'.repeat(4000)}'`;const r=extractTypeScriptSemanticContext(source,['User','UserId','loadUser']);assert.ok(r.text.includes('interface User'));assert.ok(r.text.includes('type UserId'));assert.ok(r.contextChars<r.sourceChars/2)})
test('privacy boundary removes synthetic secrets from provider text and restores locally',()=>{const raw='token=sk_1234567890abcdefghijklmnop';const r=redactProviderContext(raw);assert.equal(r.redactions.length,1);assert.equal(containsPlaintextSecret(r.providerText,r.redactions),false);assert.equal(restoreLocalText(r.providerText,r.redactions),raw)})
test('natural-language meaning enters core only through bounded structured semantic assessment',()=>{const x=parseSemanticIntentAssessment(JSON.stringify({material:true,message_kind:'constraint',task_kind:'implementation',scope:'local',risk:'low',ambiguity:'none',dependency_class:'independent',required_capabilities:['implementation'],requested_external_actions:[],likely_verification:[],likely_targets:['src/a.ts'],intent_signals:[],suppressed_intent_signals:['intent.tdd']}));assert.equal(x.message_kind,'constraint');assert.deepEqual(x.suppressed_intent_signals,['intent.tdd']);assert.throws(()=>parseSemanticIntentAssessment(JSON.stringify({...x,intent_signals:['surface.security']})),/intent signal/i)})
test('retry must be materially different',()=>{const a={failure:'test-failure',strategy:'same',tool:'npm test'};assert.equal(materiallyDifferentRetry(a,a),false);assert.equal(materiallyDifferentRetry(a,{...a,strategy:'fix fixture root cause'}),true)})
test('artifact-first result binds content to a stable hash',()=>{const s=new ContextArtifactStore(),a=s.add('audit','summary','long result',['src/a.ts']);assert.equal(a.content_hash.length,64);assert.notEqual(a.artifact_id,a.content_hash);assert.equal(s.get(a.artifact_id).content,'long result');assert.equal(s.invalidateChanged(['src/a.ts']),1);assert.equal(s.get(a.artifact_id).freshness,'POTENTIALLY_STALE')})
test('host manifest never fakes missing capabilities',()=>{assert.equal(resolveHostCapability(OPENCODE_REFERENCE_CAPABILITIES,'child_sessions'),'NATIVE');assert.equal(resolveHostCapability({host:'mock',capabilities:{}},'child_sessions'),'UNSUPPORTED')})
test('telemetry derives bounded efficiency metrics without payload capture',()=>{const x=deriveEfficiencyMetrics({taskClass:'implementation',risk:'low',executionPath:'DIRECT',roles:['coder'],skills:[],models:['auto'],tools:['edit'],topology:'single-agent',contextChars:1000,modelCalls:1,toolCalls:2,delegations:0,retries:0,verificationActions:1,failureClasses:[],escalationReasons:[],humanInteractions:0,materialHumanDecisions:0,elapsedMs:10,completed:true,productiveActions:3,totalActions:4,decisionRelevantContextChars:800});assert.equal(x.wastedComputeRatio,.25);assert.equal(x.contextEfficiency,.8)})
test('mission state records provisional then assessed adaptive execution and topology decisions',()=>{const store=new MissionStore(),m=store.start('s','update src/a.ts');assert.equal(m.identity.semantic_assessment.status,'pending');assert.ok(m.execution.ledger.some(e=>e.type==='mission.provisional'));startAssessedMission(store,'s-assessed','opaque local change',{task_kind:'implementation',scope:'local',risk:'low',required_capabilities:['implementation'],likely_targets:['src/a.ts']});const a=store.get('s-assessed');assert.equal(a.execution.adaptive_execution.path,'DIRECT');assert.equal(a.execution.topology.mode,'single-agent');assert.ok(a.execution.ledger.some(e=>e.type==='semantic.assessed'&&e.payload?.taskKind==='implementation'))})


test('storage ownership resolver keeps project-created skills OpenCode-native and Hi durable artifacts scoped',()=>{const root=mkdtempSync(join(tmpdir(),'hi-storage-'));assert.equal(projectSkillRoot(root,'hi-project-check'),join(root,'.opencode','skills','hi-project-check'));assert.equal(durableArtifactPath(root,'review','a_123'),join(root,'.opencode','hi','artifacts','review','a_123.json'))})
test('durable context artifact persistence reloads and invalidates by source file',()=>{const root=mkdtempSync(join(tmpdir(),'hi-artifact-')),s=new ContextArtifactStore(root),a=s.add('review','summary','long result',['src/a.ts']),path=durableArtifactPath(root,'review',a.artifact_id);assert.equal(existsSync(path),true);const disk=JSON.parse(readFileSync(path,'utf8'));assert.equal(disk.content_hash,a.content_hash);assert.deepEqual(disk.provenance.source_files,['src/a.ts']);assert.equal(new ContextArtifactStore(root).get(a.artifact_id)?.content,'long result');s.invalidateChanged(['src/a.ts']);assert.equal(JSON.parse(readFileSync(path,'utf8')).freshness,'POTENTIALLY_STALE')})
test('durable artifact identity is independent from content hash and source provenance',()=>{const root=mkdtempSync(join(tmpdir(),'hi-artifact-id-')),s=new ContextArtifactStore(root),a=s.add('review','same','same content',['src/a.ts']),b=s.add('review','same','same content',['src/b.ts']);assert.notEqual(a.artifact_id,b.artifact_id);assert.equal(a.content_hash,b.content_hash);assert.notEqual(a.artifact_id,a.content_hash);assert.deepEqual(new ContextArtifactStore(root).get(a.artifact_id)?.provenance.source_files,['src/a.ts']);assert.deepEqual(new ContextArtifactStore(root).get(b.artifact_id)?.provenance.source_files,['src/b.ts'])})



test('maxAgents=1 is an executable topology ceiling even when multi-agent is requested',()=>{const d=decideTopology(intent({scope:'multi-stream'}),{mode:'multi-agent',maxAgents:1,parallelism:4});assert.equal(d.mode,'single-agent');assert.equal(d.executionMode,'single');assert.equal(d.agentCount,1);assert.equal(d.parallelism,1)})
