import { mkdtempSync,existsSync,readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'
import { decideAdaptiveExecution } from '../dist/runtime/execution/adaptive-policy.js'
import { decideTopology } from '../dist/runtime/execution/topology-policy.js'
import { governContext } from '../dist/runtime/context/governor.js'
import { ProjectIntelligenceStore } from '../dist/runtime/project-intelligence/store.js'
import { extractTypeScriptSemanticContext } from '../dist/runtime/semantic/typescript-context.js'
import { redactProviderContext,containsPlaintextSecret,restoreLocalText } from '../dist/runtime/privacy/boundary.js'
import { parseSemanticIntentAssessment } from '../dist/runtime/intent/semantic-assessment.js'
import { startAssessedMission } from './helpers/semantic.mjs'
import { materiallyDifferentRetry } from '../dist/runtime/budget/mission-budget.js'
import { ArtifactStore } from '../dist/runtime/artifacts/store.js'
import { DisabledMemoryProvider } from '../dist/runtime/memory/provider.js'
import { resolveHostCapability,OPENCODE_REFERENCE_CAPABILITIES } from '../dist/runtime/host/capability-manifest.js'
import { deriveEfficiencyMetrics } from '../dist/runtime/telemetry/execution.js'
import { MissionStore } from '../dist/runtime/mission/mission-store.js'
import { projectIntelligencePath,durableArtifactPath,projectSkillRoot } from '../dist/runtime/storage/ownership.js'

const intent=(overrides={})=>({objective:'update src/a.ts',taskKind:'implementation',scope:'local',risk:'low',ambiguity:'none',dependencyClass:'independent',requiredCapabilities:['implementation'],likelyVerification:['changed-surface-sanity'],avoid:[],...overrides})

test('direct path is minimum-sufficient by default',()=>{const d=decideAdaptiveExecution(intent());assert.equal(d.path,'DIRECT');assert.equal(d.executionDepth,'minimal');assert.equal(d.contextDepth,'local');assert.equal(d.isolationDepth,'current-workspace')})
test('evidence, planned and escalated paths remain distinct',()=>{assert.equal(decideAdaptiveExecution(intent({ambiguity:'resolvable'})).path,'EVIDENCE');assert.equal(decideAdaptiveExecution(intent({scope:'multi-file',dependencyClass:'sequential'})).path,'PLANNED');assert.equal(decideAdaptiveExecution(intent({risk:'high'})).path,'ESCALATED')})
test('adaptive topology does not fan out without material benefit',()=>{assert.equal(decideTopology(intent()).mode,'single-agent');const multi=decideTopology(intent({scope:'multi-stream',dependencyClass:'independent-multi',requiredCapabilities:['implementation','multi-stream-delegation']}));assert.equal(multi.mode,'multi-agent');assert.ok(multi.agentCount>=2)})
test('explicit topology override has executable precedence',()=>{const multi=decideTopology(intent(),{mode:'multi-agent',maxAgents:4,parallelism:2});assert.equal(multi.mode,'multi-agent');assert.equal(multi.executionMode,'parallel');const single=decideTopology(intent({scope:'multi-stream'}),{mode:'single-agent',maxAgents:4,parallelism:2});assert.equal(single.mode,'single-agent');assert.equal(single.executionMode,'single')})
test('context governor protects mission state while reducing duplicate/obsolete context',()=>{const entries=[{id:'objective',kind:'objective',text:'keep objective',contextClass:'PROTECTED',createdAt:1},{id:'dup1',kind:'tool',text:'x'.repeat(900),contextClass:'PURGEABLE',createdAt:2},{id:'dup2',kind:'tool',text:'x'.repeat(900),contextClass:'PURGEABLE',createdAt:3},{id:'old',kind:'research',text:'y'.repeat(1200),contextClass:'COMPRESSIBLE',createdAt:4}];const r=governContext(entries,{maxChars:700,compressToChars:200});assert.equal(r.action,'REDUCED');assert.ok(r.entries.some(e=>e.id==='objective'));assert.ok(r.afterChars<r.beforeChars);assert.ok(r.removedIds.length>0)})
test('project intelligence becomes stale when source surface changes',()=>{const s=new ProjectIntelligenceStore();s.upsert({id:'p1',statement:'Errors use ResultEnvelope',sourceFiles:['src/errors.ts'],sourceHashes:{'src/errors.ts':'a'},confidence:.9,freshness:'FRESH',lifecycle:'ACTIVE',updatedAt:1});assert.equal(s.query('errors')[0].freshness,'FRESH');assert.deepEqual(s.invalidateChanged(['src/errors.ts']),['p1']);assert.equal(s.get('p1').freshness,'POTENTIALLY_STALE')})
test('typescript semantic context supplies requested contract without dependency graph',()=>{const source=`import x from 'x'\nconst privateThing=1\nexport interface User { id:string; name:string }\nexport type UserId = string\nexport function loadUser(id:UserId):Promise<User> { throw 0 }\n`+`const noise='${'z'.repeat(4000)}'`;const r=extractTypeScriptSemanticContext(source,['User','UserId','loadUser']);assert.ok(r.text.includes('interface User'));assert.ok(r.text.includes('type UserId'));assert.ok(r.contextChars<r.sourceChars/2)})
test('privacy boundary removes synthetic secrets from provider text and restores locally',()=>{const raw='token=sk_1234567890abcdefghijklmnop';const r=redactProviderContext(raw);assert.equal(r.redactions.length,1);assert.equal(containsPlaintextSecret(r.providerText,r.redactions),false);assert.equal(restoreLocalText(r.providerText,r.redactions),raw)})
test('natural-language meaning enters core only through bounded structured semantic assessment',()=>{const x=parseSemanticIntentAssessment(JSON.stringify({material:true,message_kind:'constraint',task_kind:'implementation',scope:'local',risk:'low',ambiguity:'none',dependency_class:'independent',required_capabilities:['implementation'],requested_external_actions:[],likely_verification:[],likely_targets:['src/a.ts'],intent_signals:[],suppressed_intent_signals:['intent.tdd']}));assert.equal(x.message_kind,'constraint');assert.deepEqual(x.suppressed_intent_signals,['intent.tdd']);assert.throws(()=>parseSemanticIntentAssessment(JSON.stringify({...x,intent_signals:['surface.security']})),/intent signal/i)})
test('retry must be materially different',()=>{const a={failure:'test-failure',strategy:'same',tool:'npm test'};assert.equal(materiallyDifferentRetry(a,a),false);assert.equal(materiallyDifferentRetry(a,{...a,strategy:'fix fixture root cause'}),true)})
test('artifact-first result binds content to a stable hash',()=>{const s=new ArtifactStore(),a=s.add('audit','summary','long result','source-a');assert.equal(a.sha256.length,64);assert.equal(s.get(a.id).content,'long result');assert.equal(s.markStaleBySource('source-a'),1);assert.equal(s.get(a.id).freshness,'POTENTIALLY_STALE')})
test('memory disabled does not affect core and performs no retrieval',async()=>{const m=new DisabledMemoryProvider();assert.deepEqual(await m.search('anything','PROJECT'),[]);assert.equal((await m.profile()).available,false)})
test('host manifest never fakes missing capabilities',()=>{assert.equal(resolveHostCapability(OPENCODE_REFERENCE_CAPABILITIES,'child_sessions'),'NATIVE');assert.equal(resolveHostCapability({host:'mock',capabilities:{}},'child_sessions'),'UNSUPPORTED')})
test('telemetry derives bounded efficiency metrics without payload capture',()=>{const x=deriveEfficiencyMetrics({taskClass:'implementation',risk:'low',executionPath:'DIRECT',roles:['coder'],skills:[],models:['auto'],tools:['edit'],topology:'single-agent',contextChars:1000,modelCalls:1,toolCalls:2,delegations:0,retries:0,verificationActions:1,failureClasses:[],escalationReasons:[],humanInteractions:0,materialHumanDecisions:0,elapsedMs:10,completed:true,productiveActions:3,totalActions:4,decisionRelevantContextChars:800});assert.equal(x.wastedComputeRatio,.25);assert.equal(x.contextEfficiency,.8)})
test('mission state records provisional then assessed adaptive execution and topology decisions',()=>{const store=new MissionStore(),m=store.start('s','update src/a.ts');assert.equal(m.semantic_assessment.status,'pending');assert.ok(m.ledger.some(e=>e.type==='mission.provisional'));startAssessedMission(store,'s-assessed','opaque local change',{task_kind:'implementation',scope:'local',risk:'low',required_capabilities:['implementation'],likely_targets:['src/a.ts']});const a=store.get('s-assessed');assert.equal(a.adaptive_execution.path,'DIRECT');assert.equal(a.topology.mode,'single-agent');assert.ok(a.ledger.some(e=>e.type==='semantic.assessed'&&e.payload?.taskKind==='implementation'))})


test('storage ownership resolver keeps project-created skills OpenCode-native and Hi durable data scoped',()=>{const root=mkdtempSync(join(tmpdir(),'hi-storage-'));assert.ok(projectSkillRoot(root,'hi-project-check').endsWith('.opencode/skills/hi-project-check'));assert.ok(projectIntelligencePath(root,'pattern-1').includes('.opencode/hi/project-intelligence/patterns/pattern-1.json'));assert.ok(durableArtifactPath(root,'review','a_123').includes('.opencode/hi/artifacts/review/a_123.json'))})
test('project intelligence persistence is lazy, source-linked, and reloads after restart',()=>{const root=mkdtempSync(join(tmpdir(),'hi-pi-')),path=projectIntelligencePath(root,'p1');assert.equal(existsSync(path),false);const s=new ProjectIntelligenceStore(root);s.upsert({id:'p1',statement:'Errors use ResultEnvelope',sourceFiles:['src/errors.ts'],sourceHashes:{'src/errors.ts':'a'},confidence:.9,freshness:'FRESH',lifecycle:'ACTIVE',updatedAt:1});assert.equal(existsSync(path),true);assert.equal(JSON.parse(readFileSync(path,'utf8')).sourceHashes['src/errors.ts'],'a');const reloaded=new ProjectIntelligenceStore(root);assert.equal(reloaded.get('p1')?.statement,'Errors use ResultEnvelope');s.invalidateChanged(['src/errors.ts']);assert.equal(JSON.parse(readFileSync(path,'utf8')).freshness,'POTENTIALLY_STALE')})
test('durable artifact persistence is lazy, kind-scoped and provenance-aware',()=>{const root=mkdtempSync(join(tmpdir(),'hi-artifact-')),s=new ArtifactStore(root),a=s.add('review','summary','long result','source-a'),path=durableArtifactPath(root,'review',a.id);assert.equal(existsSync(path),true);const disk=JSON.parse(readFileSync(path,'utf8'));assert.equal(disk.sha256,a.sha256);assert.equal(disk.sourceHash,'source-a');s.markStaleBySource('source-a');assert.equal(JSON.parse(readFileSync(path,'utf8')).freshness,'POTENTIALLY_STALE')})


test('maxAgents=1 is an executable topology ceiling even when multi-agent is requested',()=>{const d=decideTopology(intent({scope:'multi-stream'}),{mode:'multi-agent',maxAgents:1,parallelism:4});assert.equal(d.mode,'single-agent');assert.equal(d.executionMode,'single');assert.equal(d.agentCount,1);assert.equal(d.parallelism,1)})
