import test from 'node:test'
import assert from 'node:assert/strict'
import { MissionStore } from '../dist/runtime/mission/mission-store.js'
import { createToolBeforeHook } from '../dist/hooks/tool-before.js'
import { createToolAfterHook } from '../dist/hooks/tool-after.js'
import { evaluateCompletion } from '../dist/runtime/completion/evaluator.js'

function setup(objective='commit push and create release'){const store=new MissionStore('.'),m=store.start(`rv-${Math.random()}`,objective);m.changed_files=['src/a.ts'];return{m,before:createToolBeforeHook(store),after:createToolAfterHook(store)}}
const H1='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',H2='bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
async function pushOk(x,cmd='git push origin main'){await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{args:{command:cmd}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{stdout:'ok',metadata:{exit:0}})}
async function verifyPush(x,hash=H1,remoteHash=hash,remote='origin',ref='refs/heads/main'){await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'git rev-parse HEAD'}},{stdout:`${hash}\n`,metadata:{exit:0}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:`git ls-remote ${remote} ${ref}`}},{stdout:`${remoteHash}\t${ref}\n`,metadata:{exit:0}})}
async function verifyReleaseView(x,tag='v1',target='main'){await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:`gh release view ${tag} --json tagName,targetCommitish`}},{stdout:JSON.stringify({tagName:tag,targetCommitish:target}),metadata:{exit:0}})}
async function verifyRemoteTag(x,tag='v1',direct=H1,peeled,remote='origin'){const ref=`refs/tags/${tag}`;const lines=[`${direct}\t${ref}`,...(peeled?[`${peeled}\t${ref}^{}`]:[])].join('\n')+'\n';await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:`git ls-remote ${remote} ${ref} ${ref}^{}`}},{stdout:lines,metadata:{exit:0}})}

test('push exit=0 is not sufficient; release waits for matching remote ref hash',async()=>{const x=setup();await pushOk(x);assert.equal(x.m.release_chain.push.remote_verified,false);await assert.rejects(()=>x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}}),/push-remote-unverified/);await verifyPush(x);assert.equal(x.m.release_chain.push.remote_verified,true);await assert.doesNotReject(()=>x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}}))})

test('remote hash drift keeps release blocked',async()=>{const x=setup();await pushOk(x);await verifyPush(x,H1,H2);assert.equal(x.m.release_chain.push.remote_verified,false);assert.ok(x.m.blockers.includes('release-chain:push-remote-drift'));await assert.rejects(()=>x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}}),/push-remote-unverified/)})

test('implicit git push requires upstream discovery and matching probe',async()=>{const x=setup();await pushOk(x,'git push');await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'git rev-parse --abbrev-ref --symbolic-full-name @{u}'}},{stdout:'origin/main\n',metadata:{exit:0}});await verifyPush(x);assert.equal(x.m.release_chain.push.expected_remote,'origin');assert.equal(x.m.release_chain.push.expected_ref,'refs/heads/main');assert.equal(x.m.release_chain.push.remote_verified,true)})

test('release exit=0 requires both release metadata and exact remote tag commit verification',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{stdout:'released',metadata:{exit:0}});x.m.obligations.forEach(o=>o.status='closed');x.m.evidence.fresh=true;let c=evaluateCompletion(x.m);assert.ok(c.reasons.includes('release-chain:release-remote-unverified'));await verifyReleaseView(x);assert.equal(x.m.release_chain.release.view_verified,true);assert.equal(x.m.release_chain.release.remote_verified,false);await verifyRemoteTag(x);assert.equal(x.m.release_chain.release.remote_verified,true);c=evaluateCompletion(x.m);assert.ok(!c.reasons.includes('release-chain:release-remote-unverified'))})

test('wrong release tag is remote drift and remains incomplete',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{stdout:'released',metadata:{exit:0}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release view v1 --json tagName,targetCommitish'}},{stdout:JSON.stringify({tagName:'v2',targetCommitish:'main'}),metadata:{exit:0}});await verifyRemoteTag(x);assert.equal(x.m.release_chain.release.remote_verified,false);assert.ok(x.m.blockers.includes('release-chain:release-remote-drift'))})


test('annotated release tag is verified against peeled commit, not tag object sha',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{stdout:'released',metadata:{exit:0}});await verifyReleaseView(x);await verifyRemoteTag(x,'v1',H2,H1);assert.equal(x.m.release_chain.release.direct_tag_hash,H2);assert.equal(x.m.release_chain.release.peeled_tag_hash,H1);assert.equal(x.m.release_chain.release.remote_verified,true)})

test('annotated tag peeled to the wrong commit is remote drift',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{args:{command:'gh release create v1'}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release create v1'}},{stdout:'released',metadata:{exit:0}});await verifyReleaseView(x);await verifyRemoteTag(x,'v1',H1,H2);assert.equal(x.m.release_chain.release.remote_verified,false);assert.ok(x.m.blockers.includes('release-chain:release-remote-drift'))})

test('explicit release target drift cannot be hidden by a matching tag name',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);const cmd='gh release create v1 --target main';await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{args:{command:cmd}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{stdout:'released',metadata:{exit:0}});await verifyReleaseView(x,'v1','other-branch');await verifyRemoteTag(x);assert.equal(x.m.release_chain.release.remote_verified,false);assert.ok(x.m.blockers.includes('release-chain:release-remote-drift'))})

test('release parser preserves exact verification when --target precedes the tag',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);const cmd='gh release create --target main v1';await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{args:{command:cmd}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{stdout:'released',metadata:{exit:0}});assert.equal(x.m.release_chain.release.expected_tag,'v1');assert.equal(x.m.release_chain.release.expected_target,'main');await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release view --repo acme/repo v1 --json tagName,targetCommitish'}},{stdout:JSON.stringify({tagName:'v1',targetCommitish:'main'}),metadata:{exit:0}});await verifyRemoteTag(x);assert.equal(x.m.release_chain.release.remote_verified,true)})

test('release view parser handles value options before positional tag',async()=>{const x=setup('create release');await pushOk(x);await verifyPush(x);const cmd='gh release create v1';await x.before({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{args:{command:cmd}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:cmd}},{stdout:'released',metadata:{exit:0}});await x.after({sessionID:x.m.session_id,tool:'bash',args:{command:'gh release view --json tagName,targetCommitish v1'}},{stdout:JSON.stringify({tagName:'v1',targetCommitish:'main'}),metadata:{exit:0}});await verifyRemoteTag(x);assert.equal(x.m.release_chain.release.remote_verified,true)})
