import test from 'node:test'
import assert from 'node:assert/strict'
import {parseSemanticIntentAssessment} from '../dist/runtime/intent/semantic-assessment.js'
import {MissionStore} from '../dist/runtime/mission/mission-store.js'
import {renderSemanticAssessmentGate} from '../dist/runtime/intent/semantic-assessment-gate.js'

const base={material:true,message_kind:'mission',task_kind:'bug-fix',scope:'local',risk:'medium',ambiguity:'none',dependency_class:'independent',required_capabilities:['implementation','visual-qa'],requested_external_actions:[],likely_verification:['visual-check'],user_verification:[],verification_ceiling:false,likely_targets:['index.html'],intent_signals:[],suppressed_intent_signals:[],constraint_atoms:[]}
test('visual semantic contract requires bounded explicit verification cases',()=>{assert.throws(()=>parseSemanticIntentAssessment({...base,verification_cases:[]}),/visual-check requires non-empty verification_cases/);assert.throws(()=>parseSemanticIntentAssessment({...base,verification_cases:[{id:'vc_reload',subject:'reload',required_browser_actions:['reload']}]}),/invalid verification_cases/);const x=parseSemanticIntentAssessment({...base,verification_cases:[{id:'vc_reload',subject:'theme survives reload',required_browser_actions:['navigate','inspect']}]});assert.deepEqual(x.verification_cases[0].required_browser_actions,['navigate','inspect'])})
test('visual cases become canonical mission and verification obligation state',()=>{const store=new MissionStore(process.cwd()),m=store.start('visual-cases','verify UI');store.applyInitialSemanticAssessment('visual-cases',parseSemanticIntentAssessment({...base,verification_cases:[{id:'vc_reload',subject:'theme survives reload',required_browser_actions:['navigate','inspect']}]}));assert.deepEqual(m.identity.intent.verificationCases,[{id:'vc_reload',subject:'theme survives reload',required_browser_actions:['navigate','inspect']}]);assert.deepEqual(m.execution.obligations.find(o=>o.kind==='verification')?.verificationCases,m.identity.intent.verificationCases)})
test('semantic gate teaches explicit all-cases browser action coverage',()=>{const store=new MissionStore(process.cwd()),m=store.start('visual-gate','verify UI');const gate=renderSemanticAssessmentGate(m);assert.match(gate,/verification_cases/);assert.match(gate,/navigate\|click/);assert.match(gate,/one per explicit browser outcome/);assert.match(gate,/reload=navigate\+inspect/)})


test('duplicate verification case IDs fail semantic admission and resume may preserve the current case set',()=>{const cases=[{id:'vc_reload',subject:'theme survives reload',required_browser_actions:['navigate','inspect']}];assert.throws(()=>parseSemanticIntentAssessment({...base,verification_cases:[...cases,...cases]}),/ids must be unique/);const store=new MissionStore(process.cwd()),m=store.start('visual-resume-cases','verify UI');store.applyInitialSemanticAssessment('visual-resume-cases',parseSemanticIntentAssessment({...base,verification_cases:cases}));store.beginFollowupSemanticAssessment('visual-resume-cases','continue the same verification');const resume=parseSemanticIntentAssessment({...base,message_kind:'resume',verification_cases:[]});store.applyFollowupSemanticAssessment('visual-resume-cases',resume);assert.deepEqual(m.identity.intent.verificationCases,cases)})
