import {createHash} from 'node:crypto'
import {existsSync} from 'node:fs'
import {browserObservationId,type BrowserObservationAction,type BrowserObservationContract} from '../contracts/browser-observation.js'
import type {BrowserCleanupResult,BrowserExecutionContext,BrowserExecutor,BrowserInspectRequest,BrowserKeyRequest,BrowserTarget,BrowserViewportRequest,BrowserWaitRequest} from '../runtime/browser/executor.js'
import {discoverPlaywrightChromium} from '../runtime/browser/discovery.js'
export {discoverPlaywrightChromium} from '../runtime/browser/discovery.js'

export interface PlaywrightBrowserAdapterOptions{
  executable_path?:string
  headless?:boolean
  timeout_ms?:number
  persist_screenshot?:(bytes:Uint8Array,context:BrowserExecutionContext)=>string
  load_playwright?:()=>Promise<any>
  executable_exists?:(path:string)=>boolean
  browser_cache_paths?:string[]
}
type Session={browser:any;page:any;url?:string;refs:Map<number,string>;consoleErrors:string[];networkErrors:string[];executionOwnerRef:string}
const MAX_SUMMARY=4000,MAX_ERRORS=64,BROWSER_CLOSE_TIMEOUT_MS=2000
function bounded(v:string,max=MAX_SUMMARY){return v.length<=max?v:v.slice(0,max)}
async function boundedBrowserClose(browser:any,timeoutMs=BROWSER_CLOSE_TIMEOUT_MS):Promise<void>{
  let timer:ReturnType<typeof setTimeout>|undefined
  try{await Promise.race([Promise.resolve().then(()=>browser.close()),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new Error(`Playwright browser.close timed out after ${timeoutMs}ms`)),timeoutMs)})])}finally{if(timer)clearTimeout(timer)}
}
function localHost(hostname:string):boolean{return hostname==='localhost'||hostname==='127.0.0.1'||hostname==='::1'||hostname==='[::1]'}
function safeLocalUrl(value:string):string{let u:URL;try{u=new URL(value)}catch{throw new Error('Browser URL must be absolute http(s)')}if(!['http:','https:'].includes(u.protocol))throw new Error('Browser URL must use http(s)');if(u.username||u.password)throw new Error('Browser credentials in URL are forbidden');if(!localHost(u.hostname))throw new Error(`Browser target is outside supported local scope: ${u.origin}`);return u.toString()}
function plannedUrl(c:BrowserExecutionContext,value:string):string{const url=safeLocalUrl(value),origin=new URL(url).origin,allowed=new Set(c.allowed_origins??[]);if(!allowed.size)throw new Error('Browser task has no allowed-origin plan');if(!allowed.has(origin))throw new Error(`Browser target origin is outside the task plan: ${origin}`);return url}
function targetRef(value:string):number{const m=/^@e(\d{1,6})$/.exec(value);if(!m)throw new Error('Browser target must be an observed @eN reference');return Number(m[1])}
function sha(text:string):string{return createHash('sha256').update(text).digest('hex')}
export class PlaywrightBrowserAdapter implements BrowserExecutor{
  private executablePath?:string
  private readonly explicitExecutable:boolean
  private readonly browserCachePaths:string[]
  private readonly headless:boolean
  private readonly timeoutMs:number
  private readonly persistScreenshot?:PlaywrightBrowserAdapterOptions['persist_screenshot']
  private readonly loadPlaywright:()=>Promise<any>
  private readonly executableExists:(path:string)=>boolean
  private readonly sessions=new Map<string,Session>()
  constructor(options:PlaywrightBrowserAdapterOptions={}){this.executableExists=options.executable_exists??existsSync;this.explicitExecutable=Boolean(options.executable_path);this.browserCachePaths=[...new Set(options.browser_cache_paths??[])];this.executablePath=options.executable_path??discoverPlaywrightChromium(this.executableExists,this.browserCachePaths);this.headless=options.headless??true;this.timeoutMs=Math.min(Math.max(options.timeout_ms??15000,1000),30000);this.persistScreenshot=options.persist_screenshot;this.loadPlaywright=options.load_playwright??(()=>import('playwright-core'))}
  private refreshExecutable():string|undefined{if(this.executablePath&&this.executableExists(this.executablePath))return this.executablePath;if(this.explicitExecutable)return undefined;this.executablePath=discoverPlaywrightChromium(this.executableExists,this.browserCachePaths);return this.executablePath}
  private async ensure(c:BrowserExecutionContext):Promise<Session>{const current=this.sessions.get(c.task_id);if(current&&current.executionOwnerRef===c.execution_owner_ref)return current;if(current){try{await boundedBrowserClose(current.browser)}catch{}this.sessions.delete(c.task_id)}if(!c.execution_owner_ref.trim())throw new Error('Browser execution owner identity is required');const executablePath=this.refreshExecutable();if(!executablePath)throw new Error('Playwright Chromium executable is unavailable');const {chromium}=await this.loadPlaywright(),browser=await chromium.launch({executablePath,headless:this.headless,args:['--no-sandbox']}),context=await browser.newContext({acceptDownloads:false,ignoreHTTPSErrors:false});if(typeof context.route!=='function')throw new Error('Playwright request routing is required for browser origin confinement');await context.route('**/*',async(route:any)=>{try{plannedUrl(c,String(route.request().url()));await route.continue()}catch{await route.abort('blockedbyclient')}});const page=await context.newPage(),s:Session={browser,page,refs:new Map(),consoleErrors:[],networkErrors:[],executionOwnerRef:c.execution_owner_ref};page.setDefaultTimeout(this.timeoutMs);page.on('console',(msg:any)=>{if(msg.type()==='error')s.consoleErrors.push(bounded(String(msg.text()),1000));if(s.consoleErrors.length>MAX_ERRORS)s.consoleErrors.splice(0,s.consoleErrors.length-MAX_ERRORS)});page.on('requestfailed',(req:any)=>{s.networkErrors.push(bounded(`${req.method()} ${req.url()} ${req.failure()?.errorText??'failed'}`,1000));if(s.networkErrors.length>MAX_ERRORS)s.networkErrors.splice(0,s.networkErrors.length-MAX_ERRORS)});page.on('download',(download:any)=>void download.cancel().catch(()=>{}));this.sessions.set(c.task_id,s);return s}
  private observation(c:BrowserExecutionContext,s:Session|undefined,action:BrowserObservationAction,url:string,result:'OBSERVED'|'FAILED',dom?:string,screenshotRef?:string,error?:string):BrowserObservationContract{const timestamp=Date.now(),doc=dom?sha(dom):undefined,console_errors=s?.consoleErrors.slice(-MAX_ERRORS)??[],network_errors=[...(s?.networkErrors.slice(-MAX_ERRORS)??[]),...(error?[bounded(error,1000)]:[])].slice(-MAX_ERRORS),viewport=s?.page?.viewportSize?.()??undefined,o:BrowserObservationContract={observation_id:'',task_id:c.task_id,executor_version:c.executor_version,url,action,timestamp,...(viewport?{viewport:{width:Number(viewport.width),height:Number(viewport.height)}}:{}),...(doc?{document_identity:doc}:{}),...(dom?{dom_summary:bounded(dom)}:{}),console_errors,network_errors,...(screenshotRef?{screenshot_artifact_ref:screenshotRef}:{}),result};o.observation_id=browserObservationId(o);return o}
  private async snapshot(c:BrowserExecutionContext,action:BrowserObservationAction):Promise<BrowserObservationContract>{const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');try{s.url=plannedUrl(c,String(s.page.url()));const data=await s.page.locator('body').evaluate((body:any)=>{const all=[...body.querySelectorAll('a,button,input,textarea,select,[role="button"],[tabindex]')].slice(0,200);return{body:(body.innerText||'').slice(0,12000),items:all.map((el:any,i:number)=>({i:i+1,tag:String(el.tagName||'').toLowerCase(),text:String(el.innerText||el.value||el.getAttribute?.('aria-label')||'').slice(0,180)}))}});s.refs=new Map(data.items.map((x:any)=>[Number(x.i),`a,button,input,textarea,select,[role="button"],[tabindex] >> nth=${Number(x.i)-1}`]));const rendered=[bounded(String(data.body),3000),...data.items.slice(0,80).map((x:any)=>`@e${x.i} <${x.tag}> ${x.text}`)].join('\n');return this.observation(c,s,action,s.url,'OBSERVED',rendered)}catch(error){return this.observation(c,s,action,s.url,'FAILED',undefined,undefined,String(error))}}
  async health(){try{const executablePath=this.refreshExecutable();if(!executablePath)return{available:false,reason:'Playwright Chromium executable unavailable'};const pw=await this.loadPlaywright();return{available:Boolean(pw?.chromium),version:`playwright-core:${executablePath}`}}catch(error){return{available:false,reason:String(error)}}}
  async open(c:BrowserExecutionContext,url:string){const u=plannedUrl(c,url);let s:Session|undefined;try{s=await this.ensure(c);await s.page.goto(u,{waitUntil:'domcontentloaded',timeout:this.timeoutMs});s.url=u;return this.snapshot(c,'open')}catch(error){return this.observation(c,s,'open',u,'FAILED',undefined,undefined,String(error))}}
  async navigate(c:BrowserExecutionContext,url:string){const u=plannedUrl(c,url);let s=this.sessions.get(c.task_id);try{s=await this.ensure(c);await s.page.goto(u,{waitUntil:'domcontentloaded',timeout:this.timeoutMs});s.url=u;return this.snapshot(c,'navigate')}catch(error){return this.observation(c,s,'navigate',u,'FAILED',undefined,undefined,String(error))}}
  async click(c:BrowserExecutionContext,target:BrowserTarget){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');const n=targetRef(target.value),locator=s.refs.get(n);if(!locator)throw new Error('Browser target was not present in the latest bounded observation');try{await s.page.locator(locator).click({timeout:this.timeoutMs});return this.snapshot(c,'click')}catch(error){return this.observation(c,s,'click',s.url,'FAILED',undefined,undefined,String(error))}}
  async type(c:BrowserExecutionContext,target:BrowserTarget,value:string){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');if(!value||value.length>2000)throw new Error('Browser type value is required and bounded');const n=targetRef(target.value),locator=s.refs.get(n);if(!locator)throw new Error('Browser target was not present in the latest bounded observation');try{await s.page.locator(locator).fill(value,{timeout:this.timeoutMs});return this.snapshot(c,'type')}catch(error){return this.observation(c,s,'type',s.url,'FAILED',undefined,undefined,String(error))}}
  async key(c:BrowserExecutionContext,request:BrowserKeyRequest){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');const key=String(request.key??'').trim();if(!/^(?:ArrowLeft|ArrowRight|ArrowUp|ArrowDown|Enter|Space|Escape|Tab|Backspace|Delete|Home|End|PageUp|PageDown|[A-Za-z0-9])$/.test(key))throw new Error('Browser key must be one bounded navigation/action key or one alphanumeric key');try{await s.page.keyboard.press(key);return this.snapshot(c,'key')}catch(error){return this.observation(c,s,'key',s.url,'FAILED',undefined,undefined,String(error))}}
  async inspect(c:BrowserExecutionContext,request:BrowserInspectRequest={}){if(request.selector)throw new Error('Playwright browser adapter does not expose arbitrary selector inspection');return this.snapshot(c,'inspect')}
  async viewport(c:BrowserExecutionContext,request:BrowserViewportRequest){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');if(!Number.isInteger(request.width)||request.width<240||request.width>3840||!Number.isInteger(request.height)||request.height<240||request.height>2160)throw new Error('Browser viewport must be integer width 240..3840 and height 240..2160');try{await s.page.setViewportSize({width:request.width,height:request.height});return this.snapshot(c,'viewport')}catch(error){return this.observation(c,s,'viewport',s.url,'FAILED',undefined,undefined,String(error))}}
  async screenshot(c:BrowserExecutionContext){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');try{const bytes:Uint8Array=await s.page.screenshot({type:'png',fullPage:false});if(!this.persistScreenshot)return this.observation(c,s,'screenshot',s.url,'FAILED',undefined,undefined,'screenshot persistence owner unavailable');const ref=this.persistScreenshot(bytes,c);return this.observation(c,s,'screenshot',s.url,'OBSERVED',undefined,ref)}catch(error){return this.observation(c,s,'screenshot',s.url,'FAILED',undefined,undefined,String(error))}}
  async wait(c:BrowserExecutionContext,request:BrowserWaitRequest){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');if(!Number.isInteger(request.milliseconds)||request.milliseconds<0||request.milliseconds>30000)throw new Error('Browser wait must be 0..30000ms');await s.page.waitForTimeout(request.milliseconds);return this.snapshot(c,'wait')}
  async close(c:BrowserExecutionContext){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');const url=s.url;try{await boundedBrowserClose(s.browser);if(this.sessions.get(c.task_id)===s)this.sessions.delete(c.task_id);return this.observation(c,s,'close',url,'OBSERVED','browser session closed')}catch(error){return this.observation(c,s,'close',url,'FAILED',undefined,undefined,String(error))}}
  async cleanup(c:BrowserExecutionContext):Promise<BrowserCleanupResult>{const s=this.sessions.get(c.task_id);if(!s)return{cleaned:false,reason:'not-found'};if(s.executionOwnerRef!==c.execution_owner_ref)return{cleaned:false,reason:'owner-mismatch'};try{await boundedBrowserClose(s.browser);if(this.sessions.get(c.task_id)===s)this.sessions.delete(c.task_id);return{cleaned:true,reason:'cleaned'}}catch(error){return{cleaned:false,reason:'close-failed',error:String(error)}}}
  async dispose(){for(const [id,s] of this.sessions){try{await boundedBrowserClose(s.browser)}catch{}this.sessions.delete(id)}}
}
