import {createHash} from 'node:crypto'
import {existsSync,mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {browserObservationId,type BrowserObservationAction,type BrowserObservationContract} from '../contracts/browser-observation.js'
import type {BrowserCleanupResult,BrowserExecutionContext,BrowserExecutor,BrowserInspectRequest,BrowserKeyRequest,BrowserTarget,BrowserViewportRequest,BrowserWaitRequest} from '../runtime/browser/executor.js'
import {discoverPlaywrightChromium} from '../runtime/browser/discovery.js'
export {discoverPlaywrightChromium} from '../runtime/browser/discovery.js'

export interface PlaywrightBrowserAdapterOptions{
  executable_path?:string
  headless?:boolean
  timeout_ms?:number
  persist_screenshot?:(bytes:Uint8Array,context:BrowserExecutionContext)=>string
  load_playwright?:()=>Promise<any>
  executable_exists?:(path:string)=>boolean
  browser_cache_paths?:string[]
  launch_temp_base?:string
}
type Session={browser:any;page:any;url?:string;refs:Map<number,string>;consoleErrors:string[];networkErrors:string[];executionOwnerRef:string;launchTempRoot:string;invalidReason?:string;closePromise?:Promise<void>;closeState?:'pending'|'fulfilled'|'rejected';closeError?:unknown}
const MAX_SUMMARY=4000,MAX_ERRORS=64,BROWSER_CLOSE_TIMEOUT_MS=2000
class BrowserOperationTimeoutError extends Error{constructor(operation:string,timeoutMs:number){super(`Playwright ${operation} timed out after ${timeoutMs}ms`);this.name='BrowserOperationTimeoutError'}}
function bounded(v:string,max=MAX_SUMMARY){return v.length<=max?v:v.slice(0,max)}
async function boundedBrowserClose(browser:any,timeoutMs=BROWSER_CLOSE_TIMEOUT_MS):Promise<void>{
  let timer:ReturnType<typeof setTimeout>|undefined
  try{await Promise.race([Promise.resolve().then(()=>browser.close()),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new Error(`Playwright browser.close timed out after ${timeoutMs}ms`)),timeoutMs)})])}finally{if(timer)clearTimeout(timer)}
}
async function boundedSessionClose(s:Session,timeoutMs=BROWSER_CLOSE_TIMEOUT_MS):Promise<void>{
  if(!s.closePromise){const pending=Promise.resolve().then(()=>s.browser.close());s.closeState='pending';s.closePromise=pending;pending.then(()=>{s.closeState='fulfilled'},error=>{s.closeState='rejected';s.closeError=error}).catch(()=>{})}
  let timer:ReturnType<typeof setTimeout>|undefined
  try{await Promise.race([s.closePromise,new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new Error(`Playwright browser.close timed out after ${timeoutMs}ms`)),timeoutMs)})])}finally{if(timer)clearTimeout(timer)}
}
async function boundedBrowserOperation<T>(operation:string,timeoutMs:number,invoke:()=>Promise<T>):Promise<T>{
  let timer:ReturnType<typeof setTimeout>|undefined
  const pending=Promise.resolve().then(invoke);pending.catch(()=>{})
  try{return await Promise.race([pending,new Promise<T>((_resolve,reject)=>{timer=setTimeout(()=>reject(new BrowserOperationTimeoutError(operation,timeoutMs)),timeoutMs)})])}finally{if(timer)clearTimeout(timer)}
}
function localHost(hostname:string):boolean{return hostname==='localhost'||hostname==='127.0.0.1'||hostname==='::1'||hostname==='[::1]'}
function safeLocalUrl(value:string):string{let u:URL;try{u=new URL(value)}catch{throw new Error('Browser URL must be absolute http(s)')}if(!['http:','https:'].includes(u.protocol))throw new Error('Browser URL must use http(s)');if(u.username||u.password)throw new Error('Browser credentials in URL are forbidden');if(!localHost(u.hostname))throw new Error(`Browser target is outside supported local scope: ${u.origin}`);return u.toString()}
function plannedUrl(c:BrowserExecutionContext,value:string):string{const url=safeLocalUrl(value),origin=new URL(url).origin,allowed=new Set(c.allowed_origins??[]);if(!allowed.size)throw new Error('Browser task has no allowed-origin plan');if(!allowed.has(origin))throw new Error(`Browser target origin is outside the task plan: ${origin}`);return url}
function targetRef(value:string):number{const m=/^@e(\d{1,6})$/.exec(value);if(!m)throw new Error('Browser target must be an observed @eN reference');return Number(m[1])}
function sha(text:string):string{return createHash('sha256').update(text).digest('hex')}
export class PlaywrightBrowserAdapter implements BrowserExecutor{
  private executablePath?:string
  private readonly explicitExecutable:boolean
  private readonly browserCachePaths:string[]
  private readonly headless:boolean
  private readonly timeoutMs:number
  private readonly persistScreenshot?:PlaywrightBrowserAdapterOptions['persist_screenshot']
  private readonly loadPlaywright:()=>Promise<any>
  private readonly executableExists:(path:string)=>boolean
  private readonly launchTempBase:string
  private readonly sessions=new Map<string,Session>()
  private readonly retiredSessions=new Map<string,Set<Session>>()
  constructor(options:PlaywrightBrowserAdapterOptions={}){this.executableExists=options.executable_exists??existsSync;this.explicitExecutable=Boolean(options.executable_path);this.browserCachePaths=[...new Set(options.browser_cache_paths??[])];this.executablePath=options.executable_path??discoverPlaywrightChromium(this.executableExists,this.browserCachePaths);this.headless=options.headless??true;this.timeoutMs=Math.min(Math.max(options.timeout_ms??15000,1000),30000);this.persistScreenshot=options.persist_screenshot;this.loadPlaywright=options.load_playwright??(()=>import('playwright-core'));this.launchTempBase=options.launch_temp_base??(process.platform==='win32'?tmpdir():'/tmp')}
  private refreshExecutable():string|undefined{if(this.executablePath&&this.executableExists(this.executablePath))return this.executablePath;if(this.explicitExecutable)return undefined;this.executablePath=discoverPlaywrightChromium(this.executableExists,this.browserCachePaths);return this.executablePath}
  private createTempRoot():string{return mkdtempSync(join(this.launchTempBase,'hi-br-'))}
  private launchOptions(executablePath:string,temp:string){return{executablePath,headless:this.headless,timeout:this.timeoutMs,args:['--no-sandbox'],env:{...process.env,TMPDIR:temp,TMP:temp,TEMP:temp}}}
  private browserConnected(s:Session):boolean{try{return typeof s.browser?.isConnected!=='function'||Boolean(s.browser.isConnected())}catch{return false}}
  private pageClosed(s:Session):boolean{try{return typeof s.page?.isClosed==='function'&&Boolean(s.page.isClosed())}catch{return true}}
  private invalidateSession(s:Session,reason:string):void{s.invalidReason=reason;s.refs.clear()}
  private discardSession(taskID:string,s:Session):void{if(this.sessions.get(taskID)===s)this.sessions.delete(taskID);const retired=this.retiredSessions.get(taskID);if(retired){retired.delete(s);if(!retired.size)this.retiredSessions.delete(taskID)}rmSync(s.launchTempRoot,{recursive:true,force:true})}
  private retireSession(taskID:string,s:Session):void{if(this.sessions.get(taskID)===s)this.sessions.delete(taskID);let retired=this.retiredSessions.get(taskID);if(!retired){retired=new Set<Session>();this.retiredSessions.set(taskID,retired)}retired.add(s);s.closePromise?.then(()=>this.discardSession(taskID,s),()=>{if(!this.browserConnected(s))this.discardSession(taskID,s)}).catch(()=>{})}
  private matchingRetired(taskID:string,ownerRef:string):Session[]{return[...(this.retiredSessions.get(taskID)??[])].filter(s=>s.executionOwnerRef===ownerRef)}
  private liveSession(c:BrowserExecutionContext):Session{const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');if(!this.browserConnected(s)){this.discardSession(c.task_id,s);throw new Error('Browser session disconnected; call browser open or navigate to establish a fresh session')}if(this.pageClosed(s)){this.invalidateSession(s,'page-closed');throw new Error('Browser page is closed; call browser open or navigate to establish a fresh session')}if(s.invalidReason)throw new Error(`Browser session is not reusable after ${s.invalidReason}; call browser open or navigate to establish a fresh session`);return s}
  private async boundedAction<T>(c:BrowserExecutionContext,s:Session,operation:string,invoke:()=>Promise<T>,timeoutMs=this.timeoutMs):Promise<T>{try{return await boundedBrowserOperation(operation,timeoutMs,invoke)}catch(error){if(!this.browserConnected(s))this.discardSession(c.task_id,s);else if(error instanceof BrowserOperationTimeoutError)this.invalidateSession(s,`uncertain ${operation} timeout`);throw error}}
  private async closeSession(taskID:string,s:Session,allowRetire=false):Promise<'closed'|'retired'>{try{await boundedSessionClose(s)}catch(error){if(this.browserConnected(s)){this.retireSession(taskID,s);if(allowRetire)return'retired';throw error}}this.discardSession(taskID,s);return'closed'}
  private async ensure(c:BrowserExecutionContext):Promise<Session>{const current=this.sessions.get(c.task_id);if(current&&!this.browserConnected(current))this.discardSession(c.task_id,current);else if(current&&(current.invalidReason||this.pageClosed(current)))await this.closeSession(c.task_id,current,true);else if(current&&current.executionOwnerRef===c.execution_owner_ref)return current;else if(current)await this.closeSession(c.task_id,current,true);if(!c.execution_owner_ref.trim())throw new Error('Browser execution owner identity is required');const executablePath=this.refreshExecutable();if(!executablePath)throw new Error('Playwright Chromium executable is unavailable');const {chromium}=await this.loadPlaywright(),launchTempRoot=this.createTempRoot();let browser:any;try{browser=await chromium.launch(this.launchOptions(executablePath,launchTempRoot));const context=await browser.newContext({acceptDownloads:false,ignoreHTTPSErrors:false});if(typeof context.route!=='function')throw new Error('Playwright request routing is required for browser origin confinement');await context.route('**/*',async(route:any)=>{try{plannedUrl(c,String(route.request().url()));await route.continue()}catch{await route.abort('blockedbyclient')}});const page=await context.newPage(),s:Session={browser,page,refs:new Map(),consoleErrors:[],networkErrors:[],executionOwnerRef:c.execution_owner_ref,launchTempRoot};page.setDefaultTimeout(this.timeoutMs);page.on('console',(msg:any)=>{if(msg.type()==='error')s.consoleErrors.push(bounded(String(msg.text()),1000));if(s.consoleErrors.length>MAX_ERRORS)s.consoleErrors.splice(0,s.consoleErrors.length-MAX_ERRORS)});page.on('requestfailed',(req:any)=>{s.networkErrors.push(bounded(`${req.method()} ${req.url()} ${req.failure()?.errorText??'failed'}`,1000));if(s.networkErrors.length>MAX_ERRORS)s.networkErrors.splice(0,s.networkErrors.length-MAX_ERRORS)});page.on('download',(download:any)=>void download.cancel().catch(()=>{}));this.sessions.set(c.task_id,s);if(typeof browser.on==='function')browser.on('disconnected',()=>this.discardSession(c.task_id,s));if(typeof page.on==='function')page.on('close',()=>{if(this.sessions.get(c.task_id)===s)this.invalidateSession(s,'page-closed')});if(!this.browserConnected(s)){this.discardSession(c.task_id,s);throw new Error('Playwright browser disconnected during session setup')}return s}catch(error){if(browser&&this.sessions.get(c.task_id)?.browser===browser)this.sessions.delete(c.task_id);if(browser)try{await boundedBrowserClose(browser);rmSync(launchTempRoot,{recursive:true,force:true})}catch{}else rmSync(launchTempRoot,{recursive:true,force:true});throw error}}
  private observation(c:BrowserExecutionContext,s:Session|undefined,action:BrowserObservationAction,url:string,result:'OBSERVED'|'FAILED',dom?:string,screenshotRef?:string,error?:string):BrowserObservationContract{const timestamp=Date.now(),doc=dom?sha(dom):undefined,console_errors=s?.consoleErrors.slice(-MAX_ERRORS)??[],network_errors=[...(s?.networkErrors.slice(-MAX_ERRORS)??[]),...(error?[bounded(error,1000)]:[])].slice(-MAX_ERRORS),viewport=s?.page?.viewportSize?.()??undefined,o:BrowserObservationContract={observation_id:'',task_id:c.task_id,executor_version:c.executor_version,url,action,timestamp,...(viewport?{viewport:{width:Number(viewport.width),height:Number(viewport.height)}}:{}),...(doc?{document_identity:doc}:{}),...(dom?{dom_summary:bounded(dom)}:{}),console_errors,network_errors,...(screenshotRef?{screenshot_artifact_ref:screenshotRef}:{}),result};o.observation_id=browserObservationId(o);return o}
  private async snapshot(c:BrowserExecutionContext,action:BrowserObservationAction):Promise<BrowserObservationContract>{const s=this.liveSession(c);try{return await this.boundedAction(c,s,`${action} snapshot`,async()=>{s.url=plannedUrl(c,String(s.page.url()));const data=await s.page.locator('body').evaluate((body:any)=>{const all=[...body.querySelectorAll('a,button,input,textarea,select,[role="button"],[tabindex]')].slice(0,200);return{body:(body.innerText||'').slice(0,12000),items:all.map((el:any,i:number)=>({i:i+1,tag:String(el.tagName||'').toLowerCase(),text:String(el.innerText||el.value||el.getAttribute?.('aria-label')||'').slice(0,180)}))}});s.refs=new Map(data.items.map((x:any)=>[Number(x.i),`a,button,input,textarea,select,[role="button"],[tabindex] >> nth=${Number(x.i)-1}`]));const rendered=[bounded(String(data.body),3000),...data.items.slice(0,80).map((x:any)=>`@e${x.i} <${x.tag}> ${x.text}`)].join('\n');return this.observation(c,s,action,s.url!,'OBSERVED',rendered)})}catch(error){return this.observation(c,s,action,s.url!,'FAILED',undefined,undefined,String(error))}}
  async health(){let browser:any,launchTempRoot:string|undefined;try{const executablePath=this.refreshExecutable();if(!executablePath)return{available:false,reason:'Playwright Chromium executable unavailable'};const pw=await this.loadPlaywright();if(typeof pw?.chromium?.launch!=='function')return{available:false,reason:'Playwright Chromium launch primitive unavailable'};launchTempRoot=this.createTempRoot();browser=await pw.chromium.launch(this.launchOptions(executablePath,launchTempRoot));await boundedBrowserClose(browser);browser=undefined;rmSync(launchTempRoot,{recursive:true,force:true});launchTempRoot=undefined;return{available:true,version:`playwright-core:${executablePath}`}}catch(error){if(browser)try{await boundedBrowserClose(browser);browser=undefined}catch{}if(!browser&&launchTempRoot)rmSync(launchTempRoot,{recursive:true,force:true});return{available:false,reason:`Playwright Chromium launch health failed: ${String(error)}`}}}
  async open(c:BrowserExecutionContext,url:string){const u=plannedUrl(c,url);let s:Session|undefined;try{s=await this.ensure(c);await s.page.goto(u,{waitUntil:'domcontentloaded',timeout:this.timeoutMs});s.url=u;return this.snapshot(c,'open')}catch(error){return this.observation(c,s,'open',u,'FAILED',undefined,undefined,String(error))}}
  async navigate(c:BrowserExecutionContext,url:string){const u=plannedUrl(c,url);let s=this.sessions.get(c.task_id);try{s=await this.ensure(c);await s.page.goto(u,{waitUntil:'domcontentloaded',timeout:this.timeoutMs});s.url=u;return this.snapshot(c,'navigate')}catch(error){return this.observation(c,s,'navigate',u,'FAILED',undefined,undefined,String(error))}}
  async click(c:BrowserExecutionContext,target:BrowserTarget){const s=this.liveSession(c),n=targetRef(target.value),locator=s.refs.get(n);if(!locator)throw new Error('Browser target was not present in the latest bounded observation');try{await this.boundedAction(c,s,'click',()=>s.page.locator(locator).click({timeout:this.timeoutMs}));return this.snapshot(c,'click')}catch(error){return this.observation(c,s,'click',s.url!,'FAILED',undefined,undefined,String(error))}}
  async type(c:BrowserExecutionContext,target:BrowserTarget,value:string){const s=this.liveSession(c);if(!value||value.length>2000)throw new Error('Browser type value is required and bounded');const n=targetRef(target.value),locator=s.refs.get(n);if(!locator)throw new Error('Browser target was not present in the latest bounded observation');try{await this.boundedAction(c,s,'type',()=>s.page.locator(locator).fill(value,{timeout:this.timeoutMs}));return this.snapshot(c,'type')}catch(error){return this.observation(c,s,'type',s.url!,'FAILED',undefined,undefined,String(error))}}
  async key(c:BrowserExecutionContext,request:BrowserKeyRequest){const s=this.liveSession(c),key=String(request.key??'').trim();if(!/^(?:ArrowLeft|ArrowRight|ArrowUp|ArrowDown|Enter|Space|Escape|Tab|Backspace|Delete|Home|End|PageUp|PageDown|[A-Za-z0-9])$/.test(key))throw new Error('Browser key must be one bounded navigation/action key or one alphanumeric key');try{await this.boundedAction(c,s,'key',()=>s.page.keyboard.press(key));return this.snapshot(c,'key')}catch(error){return this.observation(c,s,'key',s.url!,'FAILED',undefined,undefined,String(error))}}
  async inspect(c:BrowserExecutionContext,request:BrowserInspectRequest={}){if(request.selector)throw new Error('Playwright browser adapter does not expose arbitrary selector inspection');return this.snapshot(c,'inspect')}
  async viewport(c:BrowserExecutionContext,request:BrowserViewportRequest){const s=this.liveSession(c);if(!Number.isInteger(request.width)||request.width<240||request.width>3840||!Number.isInteger(request.height)||request.height<240||request.height>2160)throw new Error('Browser viewport must be integer width 240..3840 and height 240..2160');try{await this.boundedAction(c,s,'viewport',()=>s.page.setViewportSize({width:request.width,height:request.height}));return this.snapshot(c,'viewport')}catch(error){return this.observation(c,s,'viewport',s.url!,'FAILED',undefined,undefined,String(error))}}
  async screenshot(c:BrowserExecutionContext){const s=this.liveSession(c);try{const bytes:Uint8Array=await this.boundedAction(c,s,'screenshot',()=>s.page.screenshot({type:'png',fullPage:false,timeout:this.timeoutMs}));if(!this.persistScreenshot)return this.observation(c,s,'screenshot',s.url!,'FAILED',undefined,undefined,'screenshot persistence owner unavailable');const ref=this.persistScreenshot(bytes,c);return this.observation(c,s,'screenshot',s.url!,'OBSERVED',undefined,ref)}catch(error){return this.observation(c,s,'screenshot',s.url!,'FAILED',undefined,undefined,String(error))}}
  async wait(c:BrowserExecutionContext,request:BrowserWaitRequest){const s=this.liveSession(c);if(!Number.isInteger(request.milliseconds)||request.milliseconds<0||request.milliseconds>30000)throw new Error('Browser wait must be 0..30000ms');await this.boundedAction(c,s,'wait',()=>s.page.waitForTimeout(request.milliseconds),Math.min(60_000,request.milliseconds+this.timeoutMs));return this.snapshot(c,'wait')}
  async close(c:BrowserExecutionContext){const s=this.sessions.get(c.task_id);if(!s?.url||s.executionOwnerRef!==c.execution_owner_ref)throw new Error('Browser session is not owned by the current execution identity');const url=s.url;try{await this.closeSession(c.task_id,s);return this.observation(c,s,'close',url,'OBSERVED','browser session closed')}catch(error){return this.observation(c,s,'close',url,'FAILED',undefined,undefined,String(error))}}
  async cleanup(c:BrowserExecutionContext):Promise<BrowserCleanupResult>{const active=this.sessions.get(c.task_id),retired=this.matchingRetired(c.task_id,c.execution_owner_ref),owned=[...(active?.executionOwnerRef===c.execution_owner_ref?[active]:[]),...retired];if(!owned.length)return active?{cleaned:false,reason:'owner-mismatch'}:{cleaned:false,reason:'not-found'};let failure:unknown;for(const s of owned)try{await this.closeSession(c.task_id,s)}catch(error){failure??=error}if(failure)return{cleaned:false,reason:'close-failed',error:String(failure)};return{cleaned:true,reason:'cleaned'}}
  async dispose(){for(const [id,s] of [...this.sessions])try{await this.closeSession(id,s)}catch{}for(const [id,set] of [...this.retiredSessions])for(const s of [...set])try{await this.closeSession(id,s)}catch{}}
}
