import type { EvidenceItem,EvidenceOutcome,MissionState } from '../mission/types.js'
import type { MissionEvidenceKind } from '../../contracts/evidence.js'
import { appendLedger } from '../ledger/ledger.js'
function id():string{return`ev_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
const WRITE_TOOLS=new Set(['write','edit','patch','apply_patch','multiedit'])
const SHELL_MUTATION_COMMAND=/(?:^|[;&|]\s*)(?:rm|mv|cp|touch|mkdir|rmdir|chmod|chown|chgrp|ln|truncate|dd|install|patch|rsync|tee|sed\s+-i|perl\s+-pi|python[^\n]*(?:\bwrite\b|\bopen\s*\([^)]*,\s*['"]?[wa+])|node[^\n]*(?:writeFileSync|writeFile|appendFileSync|appendFile|renameSync|rename|unlinkSync|unlink|mkdirSync|mkdir|rmSync|chmodSync|chmod)|git\s+(?:apply|am|checkout|switch|merge|rebase|cherry-pick|restore|reset|clean|stash)|npm\s+(?:install|uninstall|update|run\s+build)|pnpm\s+(?:add|remove|install|update|build)|yarn\s+(?:add|remove|install|build)|bun\s+(?:add|remove|install|build)|make(?:\s|$)|cmake\s+--build)\b/i
const SHELL_REDIRECTION=/(?:^|[^<>])(?:>>?|2>>?|1>>?)\s*[^&|]/
function shellMayMutate(command:string):boolean{return SHELL_MUTATION_COMMAND.test(command)||SHELL_REDIRECTION.test(command)}
const VERIFY_HINT=/(test|pytest|vitest|jest|npm\s+test|pnpm\s+test|bun\s+test|cargo\s+test|go\s+test|lint|build|typecheck|check)/i
function verificationKind(command:string):MissionEvidenceKind{if(/test|pytest|vitest|jest|spec|go\s+test|cargo\s+test/i.test(command))return'targeted-tests';if(/typecheck|tsc\b|mypy|pyright/i.test(command))return'typecheck';if(/lint|eslint|ruff/i.test(command))return'lint';if(/build|compile|cargo\s+check/i.test(command))return'build';return'changed-surface-sanity'}
function numericExit(output:any):number|undefined{for(const v of [output?.metadata?.exit,output?.metadata?.exitCode,output?.metadata?.exit_code,output?.exit,output?.exitCode,output?.exit_code]){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'&&/^-?\d+$/.test(v.trim()))return Number(v)}return undefined}
const ENVIRONMENT_FAILURE=/(command not found|not recognized as an internal|no module named|cannot find module|module not found|missing dependency|enoent|spawn .* (?:not found|failed)|executable .* not found|permission denied|eacces|network.*unreachable|temporary failure in name resolution|connection refused|connection reset|socket hang|timed?\s*out|timeout|unable to resolve host|could not resolve host|certificate (?:verify|verification)|tls handshake)/i
function outcomeOf(output:any,text:string):{outcome:EvidenceOutcome;reason?:string}{const exit=numericExit(output);if(ENVIRONMENT_FAILURE.test(text))return{outcome:'environment-issue',reason:'verification-environment-unavailable'};if(exit!==undefined)return{outcome:exit===0?'passed':'failed',reason:exit===0?undefined:`verification-exit-${exit}`};if(/(^|\n)\s*(fail|failed|error)|exit\s*code\s*[1-9]/i.test(text))return{outcome:'failed',reason:'verification-reported-failure'};return{outcome:'pending',reason:'verification-exit-unknown'}}
export function markMutation(mission:MissionState,files:string[]=[],source='tool'):void{const now=Date.now();mission.evidence.last_mutation_at=now;mission.evidence.fresh=false;for(const item of mission.evidence.items)if(!item.invalidated_at)item.invalidated_at=now;mission.changed_files=[...new Set([...mission.changed_files,...files])];appendLedger(mission,'file.changed',{payload:{source,files}})}
export function addEvidence(mission:MissionState,input:Omit<EvidenceItem,'id'|'observed_at'> & {observed_at?:number}):EvidenceItem{const item:EvidenceItem={id:id(),observed_at:input.observed_at??Date.now(),kind:input.kind,summary:input.summary,scope:input.scope,source:input.source,source_session_id:input.source_session_id,source_state_hash:input.source_state_hash,task_id:input.task_id,obligation_ids:input.obligation_ids,pass:input.pass,outcome:input.outcome??(input.pass===true?'passed':input.pass===false?'failed':undefined),reason:input.reason,invalidated_at:input.invalidated_at};mission.evidence.items.push(item);if(mission.evidence.items.length>100)mission.evidence.items.splice(0,mission.evidence.items.length-100);const mutation=mission.evidence.last_mutation_at??0;mission.evidence.fresh=mission.evidence.items.some(e=>(e.outcome==='passed'||e.pass===true)&&!e.invalidated_at&&e.observed_at>=mutation);appendLedger(mission,item.outcome==='failed'?'verification.fail':item.outcome==='environment-issue'?'verification.environment-issue':'verification.pass',{payload:{kind:item.kind,summary:item.summary,reason:item.reason,source_session_id:item.source_session_id,source_state_hash:item.source_state_hash,task_id:item.task_id,obligation_ids:item.obligation_ids}});return item}
export function observeToolBefore(mission:MissionState,tool:string,args:any):void{if(WRITE_TOOLS.has(tool)){const files=[args?.filePath,args?.path,args?.file].filter((x):x is string=>typeof x==='string');markMutation(mission,files,tool);return}const command=typeof args?.command==='string'?args.command:'';if(tool==='bash'&&shellMayMutate(command))markMutation(mission,[],'bash-mutation')}
export function observeToolAfter(mission:MissionState,tool:string,args:any,output:any):void{if(WRITE_TOOLS.has(tool))return;const command=typeof args?.command==='string'?args.command:'';if(tool==='read'&&mission.intent.taskKind==='review'){const path=typeof args?.filePath==='string'?args.filePath:typeof args?.path==='string'?args.path:undefined;const text=typeof output==='string'?output:JSON.stringify(output??'');if(text.trim()&&!/(error|failed)/i.test(text))addEvidence(mission,{kind:'review-input',summary:path?('Read '+path):'Read-only review input',scope:path?[path]:[],source:'read',pass:true,outcome:'passed'})}if(tool==='skill'&&mission.intent.taskKind==='review'){const text=typeof output==='string'?output:JSON.stringify(output??'');if(text.trim()&&!/(error|failed)/i.test(text))addEvidence(mission,{kind:'review-input',summary:'Native skill content loaded',scope:[],source:'skill',pass:true,outcome:'passed'})}if(tool==='bash'&&mission.intent.taskKind==='review'&&!shellMayMutate(command)){const text=typeof output==='string'?output:JSON.stringify(output??''),exit=numericExit(output);if(text.trim()&&(exit===undefined||exit===0)&&!/(error|failed)/i.test(text))addEvidence(mission,{kind:'review-input',summary:'Read-only command: '+command.slice(0,180),scope:[],source:'bash',pass:true,outcome:'passed'})}if(tool==='bash'&&VERIFY_HINT.test(command)){const text=typeof output==='string'?output:JSON.stringify(output??''),out=outcomeOf(output,text);addEvidence(mission,{kind:verificationKind(command),summary:command.slice(0,180),scope:mission.changed_files,source:'bash',pass:out.outcome==='passed'?true:out.outcome==='failed'?false:undefined,outcome:out.outcome,reason:out.reason})}}
