import test from 'node:test'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,chmodSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {AuthoritativeRunLock,reconcileAuthoritativeRun,reconcileContinuation} from '../scripts/workload-acceptance/authoritative-run.mjs'
import {FixtureManager,fixtureIdentity} from '../scripts/workload-acceptance/fixture-manager.mjs'
import {ImmutableReceiptWriter,admitRerunLineage} from '../scripts/workload-acceptance/receipts.mjs'
import {selectTestModel,expandTestPool,effectiveWModelIds} from '../scripts/workload-acceptance/model-pool.mjs'
import {roleAcceptanceObservation} from '../scripts/workload-acceptance/role-observation.mjs'
import {assertWorkloadSpec,assertHiddenOracle,oracleIdentity} from '../scripts/workload-acceptance/workload-spec.mjs'
import {assessHarnessLiveness} from '../scripts/workload-acceptance/liveness-adapter.mjs'
import {OwnedProcessManager} from '../scripts/workload-acceptance/process-owner.mjs'
import {classify,productRepairAuthorized} from '../scripts/workload-acceptance/classification.mjs'
import {cleanupOwnedResources} from '../scripts/workload-acceptance/cleanup.mjs'
import {normalizeLiveModels,parseVerboseModelInventory,missionTerminalStatus,modelIdentity,writeSourcePluginConfig,writeWModelConfinement,outOfPoolWorkerModels,resolveExecutionContract,resolveRuntimeIdentity,assertOperatorRuntimeSeparation,requireReadyAdmission,discoverTerminalPredecessor,buildRuntimeEnvironment,classifyWPermissionRequest,W_PRIMARY_AGENT} from '../scripts/workload-acceptance/execution-driver.mjs'
import {WORKLOAD_IDS,parseCanonicalPromptCatalog,buildCatalogManifest,resolveCatalogEntry} from '../scripts/workload-acceptance/catalog.mjs'


const temp=()=>mkdtempSync(join(process.cwd(),'.agent-work/tmp/w-harness-selftest-'))

async function withLock(t,fn){const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const lock=new AuthoritativeRunLock(join(root,'run.lock'),{workloadId:'WT',runId:'run-a'});await lock.acquire();t.after(()=>lock.release());return fn({root,lock})}

test('duplicate invocation is rejected before fixture mutation',async t=>withLock(t,async({root})=>{let mutated=false;const contender=new AuthoritativeRunLock(join(root,'run.lock'),{workloadId:'WT',runId:'run-b'});await assert.rejects(()=>contender.acquire(),/AUTHORITATIVE_RUN_LOCKED/);assert.equal(mutated,false)}))

test('stale lock metadata plus dead owner reconciles without treating lock file existence as live',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const path=join(root,'run.lock');writeFileSync(path,'');writeFileSync(path+'.meta.json',JSON.stringify({workload_id:'WT',run_id:'old',holder_pid:99999999}));const r=await reconcileAuthoritativeRun({lockPath:path,workloadId:'WT',processProbe:()=>false,sessionProbe:async()=> 'idle'});assert.equal(r.disposition,'STALE_RECONCILED')})

test('live authoritative run reconnect is adopted/waited, never duplicate-dispatched',async t=>withLock(t,async({root,lock})=>{const r=await reconcileAuthoritativeRun({lockPath:join(root,'run.lock'),workloadId:'WT',processProbe:pid=>pid===lock.holderPid,sessionProbe:async()=> 'busy'});assert.equal(r.disposition,'ADOPT_WAIT');assert.equal(r.run_id,'run-a')}))

test('ambiguous owner blocks a new run fail-closed',async t=>withLock(t,async({root})=>{const meta=join(root,'run.lock.meta.json');const x=JSON.parse(readFileSync(meta));x.holder_pid=123456789;writeFileSync(meta,JSON.stringify(x));const r=await reconcileAuthoritativeRun({lockPath:join(root,'run.lock'),workloadId:'WT',processProbe:()=>false,sessionProbe:async()=> 'unknown'});assert.equal(r.disposition,'AMBIGUOUS_BLOCKED')}))

test('fixture reset is impossible before authoritative lock ownership',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));let calls=0;const fm=new FixtureManager({workloadId:'WT',fixtureRoot:join(root,'fixture'),baseline:{kind:'sha256',value:'abc'},reset:async()=>{calls++}});await assert.rejects(()=>fm.reset(),/AUTHORITATIVE_LOCK_REQUIRED/);assert.equal(calls,0)})

test('immutable receipts and run lineage reject overwrite',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const w=new ImmutableReceiptWriter(join(root,'runs','r1','receipts'),'r1');const first=w.write('run-identity',{run_id:'r1'});assert.ok(first.sha256);assert.throws(()=>w.write('run-identity',{run_id:'r1'}),/IMMUTABLE_RECEIPT_EXISTS/)})

test('same-condition blind rerun is rejected without repair or material transient change',()=>{assert.throws(()=>admitRerunLineage({predecessorRunId:'r1',predecessorCondition:'x',currentCondition:'x'}),/BLIND_RERUN_FORBIDDEN/);assert.equal(admitRerunLineage({predecessorRunId:'r1',predecessorCondition:'x',currentCondition:'x',repairReceipt:'repair.json'}).allowed,true)})

test('development pool filters capabilities before test-only cost rank',()=>{const selected=selectTestModel({liveInventory:[{id:'cheap',capabilities:['text']},{id:'vision',capabilities:['text','image']}],pool:[{id:'cheap',costRank:1},{id:'vision',costRank:9}],requiredCapabilities:['image']});assert.equal(selected.model.id,'vision');assert.equal(selected.reason,'capability-eligible-test-cost-order')})

test('test model pool remains a harness input and does not write product routing state',()=>{const cfg={pool:[{id:'x',costRank:1}]};const selected=selectTestModel({liveInventory:[{id:'x',capabilities:['text']}],pool:cfg.pool,requiredCapabilities:['text']});assert.equal(selected.model.id,'x');assert.deepEqual(Object.keys(selected).sort(),['eligible','model','reason','rejected'])})

test('W test pool preserves configured ten preference entries and appends only objectively zero-cost live models provider-agnostically',()=>{const configured=[{id:'opencode-go/muse',costRank:1},{id:'opencode-go/pro',costRank:2}],live=[{id:'opencode-go/muse',capabilities:['text'],zeroCost:false},{id:'opencode/free-a',capabilities:['text'],zeroCost:true},{id:'openrouter/free-b',capabilities:['text'],zeroCost:true},{id:'zen/paid',capabilities:['text'],zeroCost:false}];const pool=expandTestPool(configured,live);assert.deepEqual(pool.map(x=>x.id),['opencode-go/muse','opencode-go/pro','opencode/free-a','openrouter/free-b']);assert.ok(pool.find(x=>x.id==='openrouter/free-b').costRank>2)})

test('verbose inventory marks free only from numeric zero-cost metadata, never model naming',()=>{const rows=normalizeLiveModels([{id:'free-name-but-paid',providerID:'p',cost:{input:1,output:0},capabilities:{input:{text:true},output:{text:true}}},{id:'ordinary-name',providerID:'q',cost:{input:0,output:0,cache:{read:0,write:0}},capabilities:{input:{text:true},output:{text:true}}}]);assert.equal(rows[0].zeroCost,false);assert.equal(rows[1].zeroCost,true)})


test('role observation records expected and actual independently without injecting role authority',()=>{const o=roleAcceptanceObservation({taskId:'t1',semantics:['external-research'],requiredCapabilities:['research'],expectedRole:'researcher',actualRole:'coder',permissionProfile:'read-only',methodologies:['m'],tools:['read'],evidenceOwner:'w1',selectedModel:'x'});assert.equal(o.expected_role,'researcher');assert.equal(o.actual_role,'coder');assert.equal(o.role_match,false)})

test('hidden oracle must be outside fixture and inaccessible by group/world mode',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture'),control=join(root,'control');mkdirSync(fixture);mkdirSync(control);const oracle=join(control,'oracle.mjs');writeFileSync(oracle,'process.exit(0)');chmodSync(oracle,0o600);assert.doesNotThrow(()=>assertHiddenOracle({oraclePath:oracle,fixtureRoot:fixture,harnessRoot:join(root,'harness')}));const leaked=join(fixture,'oracle.mjs');writeFileSync(leaked,'');chmodSync(leaked,0o600);assert.throws(()=>assertHiddenOracle({oraclePath:leaked,fixtureRoot:fixture,harnessRoot:join(root,'harness')}),/ORACLE_ISOLATION_VIOLATION/)})

test('oracle identity binds exact version and fixture baseline',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const p=join(root,'oracle');writeFileSync(p,'oracle-v1');const a=oracleIdentity({path:p,version:'v1',fixtureIdentity:'f1'}),b=oracleIdentity({path:p,version:'v2',fixtureIdentity:'f1'});assert.notEqual(a.identity,b.identity);assert.equal(a.fixture_identity,'f1')})

test('workload spec contract is declarative and requires explicit fixture seed/reset/ownership surfaces',()=>{const valid={id:'WT',title:'self-test',difficulty:'test',visiblePrompt:'prompt.txt',fixture:{root:'fixture',seed:'seed',resetProcedure:'copy immutable seed under authoritative lock',baseline:{kind:'sha256',value:'x'},allowedMutation:['**']},requiredCapabilities:['text'],runtimeCapabilities:['node'],hiddenOracle:{path:'control/oracle.mjs',version:'1'},requiredEvidence:['targeted-tests'],cleanup:{ownedOnly:true,preserveFixtureAfterTerminalForInspection:true},seededConditions:[]};assert.doesNotThrow(()=>assertWorkloadSpec(valid));assert.throws(()=>assertWorkloadSpec({...valid,fixture:{...valid.fixture,seed:undefined}}),/WORKLOAD_SPEC_FIXTURE_CONTRACT_INVALID/);assert.throws(()=>assertWorkloadSpec({...valid,fixture:{...valid.fixture,resetProcedure:{immutableSeed:'seed'}}}),/WORKLOAD_SPEC_FIXTURE_CONTRACT_INVALID/)})

test('harness consumes product liveness: >120s busy is not stalled',async()=>{const m={identity:{status:'active',created_at:0},continuation:{generation:1},execution:{ledger:[],workers:[{id:'w',task_id:'t',status:'busy',session_id:'s',generation_at_spawn:1}],processes:[]}};const r=assessHarnessLiveness(m,{now:180000,hostSessions:{s:'busy'}});assert.notEqual(r.state,'STALLED');assert.equal(r.inflight,'YES')})

test('harness exposes product liveness no-progress + inflight NO stall',()=>{const m={identity:{status:'active',created_at:0},continuation:{generation:1},execution:{ledger:[],workers:[],processes:[]}};const r=assessHarnessLiveness(m,{now:180000,hostSessions:{}});assert.equal(r.state,'STALLED');assert.equal(r.inflight,'NO')})

test('PID alive alone is not harness inflight authority',()=>{const m={identity:{status:'active',created_at:0},continuation:{generation:1},execution:{ledger:[],workers:[],processes:[{process_id:'p',status:'RUNNING'}]}};const r=assessHarnessLiveness(m,{now:180000,processes:{p:{pid_alive:true,owner_verified:false,status:'running'}}});assert.equal(r.inflight,'UNKNOWN');assert.equal(r.destructive_recovery_allowed,false)})

test('process owner mismatch quarantines instead of signalling',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const pm=new OwnedProcessManager(root);const p=await pm.spawn({runId:'r1',workloadId:'WT',command:process.execPath,args:['-e','setInterval(()=>{},1000)'],cwd:root,readiness:{kind:'delay',ms:20}});const result=await pm.terminate({...p,command_identity:'wrong'});assert.equal(result.disposition,'QUARANTINED');assert.equal(result.signalled,false);process.kill(-p.pgid,'SIGKILL')})

test('cleanup touches only resources owned by the exact run',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const owned=join(root,'owned'),foreign=join(root,'foreign');mkdirSync(owned);mkdirSync(foreign);const result=await cleanupOwnedResources('r1',[{kind:'path',path:owned,ownerRunId:'r1',root},{kind:'path',path:foreign,ownerRunId:'r2',root}]);assert.equal(existsSync(owned),false);assert.equal(existsSync(foreign),true);assert.equal(result.skipped.length,1)})

test('classification admits product repair only for mechanically evidenced PRODUCT_DEFECT',()=>{const c=classify('PRODUCT_DEFECT',{evidenceRefs:['e1'],rootCause:'canonical invariant violated'});assert.equal(productRepairAuthorized(c),true);assert.throws(()=>classify('PRODUCT_DEFECT',{evidenceRefs:[],rootCause:''}),/PRODUCT_DEFECT_REQUIRES_MECHANICAL_PROOF/)})

test('MODEL_BEHAVIOR can be terminal workload evidence but never product mutation authority',()=>{const c=classify('MODEL_BEHAVIOR',{evidenceRefs:['run/result']});assert.equal(productRepairAuthorized(c),false);assert.equal(c.terminal_allowed,true)})

import {resolveToolPreflight} from '../scripts/workload-acceptance/tool-preflight.mjs'
import {promptIdentity} from '../scripts/workload-acceptance/workload-spec.mjs'
import {runHiddenOracle,oracleInvalidationLineage} from '../scripts/workload-acceptance/oracle-runner.mjs'
import {executionObservation} from '../scripts/workload-acceptance/execution-observation.mjs'

test('tool preflight consumes a canonical resolver result instead of bypassing tool policy',async()=>{const r=await resolveToolPreflight(['browser','php'],async cap=>cap==='browser'?{status:'existing',implementationId:'playwright',smokeReceipt:'r1'}:{status:'blocked',reason:'missing'});assert.deepEqual(r.blocked,['php']);assert.equal(r.resolutions[0].smoke_receipt,'r1')})

test('prompt identity hashes only the visible prompt source',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const p=join(root,'prompt.txt');writeFileSync(p,'visible user request\n');const i=promptIdentity(p);assert.match(i.sha256,/^[a-f0-9]{64}$/);assert.equal(i.path,p)})

test('oracle runner returns hash-bound immutable observation without classifying product defects',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture'),control=join(root,'control');mkdirSync(fixture);mkdirSync(control);const script=join(control,'oracle.mjs');writeFileSync(script,"console.log(JSON.stringify({pass:true,checks:3}))\n");chmodSync(script,0o600);const r=await runHiddenOracle({oraclePath:script,fixtureRoot:fixture,harnessRoot:join(root,'harness'),command:process.execPath,args:[script],cwd:root,identity:'oracle-id',fixtureIdentity:'fixture-id',timeoutMs:2000});assert.equal(r.exit_code,0);assert.equal(r.oracle_identity,'oracle-id');assert.equal('classification' in r,false);assert.match(r.stdout_sha256,/^[a-f0-9]{64}$/)})

test('bounded process readiness probe gates acceptance without becoming a workload wall timeout',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const pm=new OwnedProcessManager(root);let probes=0;const p=await pm.spawn({runId:'r1',workloadId:'WT',command:process.execPath,args:['-e','setInterval(()=>{},1000)'],cwd:root,readiness:{kind:'probe',timeoutMs:500,intervalMs:10,probe:async()=>++probes>=2}});assert.ok(probes>=2);const x=await pm.terminate(p,{graceMs:100});assert.equal(x.signalled,true)})

test('execution observation preserves runtime truth without inventing a second task/worker owner',()=>{const x=executionObservation({sessionId:'s',tasks:[{id:'t',status:'running',role:'coder',worker_id:'w'}],workers:[{id:'w',task_id:'t',status:'busy',role:'coder',session_id:'c',generation_at_spawn:2,attempt:1,model:'m'}],processes:[]});assert.deepEqual(x.tasks,[{id:'t',status:'running',role:'coder',worker_id:'w'}]);assert.equal(x.workers[0].generation,2)})


test('continuation reconciliation blocks mismatched run-meta/runtime/receipt identity before a new run',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const r=await reconcileContinuation({lockPath:join(root,'run.lock'),workloadId:'WT',runMetaProbe:async()=>({status:'terminal',run_id:'r1'}),runtimeStateProbe:async()=>({status:'terminal',run_id:'r2'}),receiptProbe:async()=>({status:'terminal',run_id:'r1'})});assert.equal(r.disposition,'AMBIGUOUS_BLOCKED');assert.equal(r.reason,'continuation-run-id-mismatch')})

test('oracle identity change requires explicit invalidation lineage',()=>{const x=oracleInvalidationLineage({priorRunId:'r1',oldOracleIdentity:'o1',newOracleIdentity:'o2',reason:'oracle defect repair'});assert.equal(x.prior_result_invalidated,true);assert.throws(()=>oracleInvalidationLineage({priorRunId:'r1',oldOracleIdentity:'o1',newOracleIdentity:'o1',reason:'x'}),/ORACLE_INVALIDATION_LINEAGE_INVALID/)})

import {smokeOracleDeterminism} from '../scripts/workload-acceptance/oracle-runner.mjs'
import {WorkloadAcceptanceHarness} from '../scripts/workload-acceptance/harness-core.mjs'

test('common harness acquires OS lock before fixture reset and writes immutable preflight receipts',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture');mkdirSync(fixture);writeFileSync(join(fixture,'a.txt'),'baseline\n');const baseline=fixtureIdentity(fixture),stateRoot=join(root,'state');let resetObservedHeld=false;const harness=new WorkloadAcceptanceHarness({stateRoot,productIdentity:{head:'abc'},liveInventory:[],sessionProbe:async()=> 'idle',processProbe:()=>false});const spec={id:'WT',title:'self-test',difficulty:'test',visiblePrompt:'prompt.txt',fixture:{root:fixture,seed:fixture,resetProcedure:'reset under authoritative lock',baseline:{kind:'sha256',value:baseline},allowedMutation:['a.txt']},requiredCapabilities:['text'],runtimeCapabilities:['node'],hiddenOracle:{path:'control/oracle.mjs',version:'1'},requiredEvidence:['targeted-tests'],cleanup:{ownedOnly:true,preserveFixtureAfterTerminalForInspection:true},seededConditions:[]};const run=await harness.preflight(spec,{conditionFingerprint:'cond-1',prepareFixture:async()=>{const {spawnSync}=await import('node:child_process');resetObservedHeld=spawnSync('flock',['-n',join(stateRoot,'WT','authoritative.lock'),'true']).status!==0}});t.after(()=>run.lock.release());assert.equal(run.disposition,'READY_TO_EXECUTE');assert.equal(resetObservedHeld,true);assert.equal(run.receipts.read('run-identity').workload_id,'WT');assert.equal(run.receipts.read('fixture-identity').observed_identity,baseline)})


test('execution admission consumes exact producer run_id and verifies receipt identity before dispatch',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture');mkdirSync(fixture);writeFileSync(join(fixture,'a.txt'),'baseline\n');const baseline=fixtureIdentity(fixture),stateRoot=join(root,'state'),harness=new WorkloadAcceptanceHarness({stateRoot,productIdentity:{head:'abc'},liveInventory:[],sessionProbe:async()=> 'idle',processProbe:()=>false}),spec={id:'WT',title:'self-test',difficulty:'test',visiblePrompt:'prompt.txt',fixture:{root:fixture,seed:fixture,resetProcedure:'reset under authoritative lock',baseline:{kind:'sha256',value:baseline},allowedMutation:['a.txt']},requiredCapabilities:['text'],runtimeCapabilities:['node'],hiddenOracle:{path:'control/oracle.mjs',version:'1'},requiredEvidence:['targeted-tests'],cleanup:{ownedOnly:true},seededConditions:[]};const run=await harness.preflight(spec,{conditionFingerprint:'cond-admission'});t.after(()=>run.lock.release());const admitted=requireReadyAdmission(run);assert.equal(admitted.runId,run.run_id);assert.equal(admitted.runId,run.receipts.read('run-identity').run_id);assert.equal(admitted.runId,run.lock.runId);assert.throws(()=>requireReadyAdmission({...run,run_id:'other'}),/READY_ADMISSION_RUN_ID_MISMATCH/);assert.throws(()=>requireReadyAdmission({...run,run_id:undefined}),/READY_ADMISSION_RUN_ID_MISSING/)})


test('common preflight persists exact condition fingerprint and immutable rerun lineage',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture');mkdirSync(fixture);writeFileSync(join(fixture,'a.txt'),'baseline\n');const baseline=fixtureIdentity(fixture),stateRoot=join(root,'state'),harness=new WorkloadAcceptanceHarness({stateRoot,productIdentity:{head:'abc'},liveInventory:[],sessionProbe:async()=> 'idle',processProbe:()=>false}),spec={id:'WT',title:'self-test',difficulty:'test',visiblePrompt:'prompt.txt',fixture:{root:fixture,seed:fixture,resetProcedure:'reset under authoritative lock',baseline:{kind:'sha256',value:baseline},allowedMutation:['a.txt']},requiredCapabilities:['text'],runtimeCapabilities:['node'],hiddenOracle:{path:'control/oracle.mjs',version:'1'},requiredEvidence:['targeted-tests'],cleanup:{ownedOnly:true},seededConditions:[]};const run=await harness.preflight(spec,{conditionFingerprint:'cond-lineage'});t.after(()=>run.lock.release());assert.equal(run.receipts.read('run-identity').condition_fingerprint,'cond-lineage');const lineage=run.receipts.read('lineage');assert.equal(lineage.condition_fingerprint,'cond-lineage');assert.equal(lineage.predecessor_run_id,null);assert.equal(lineage.reason,'initial-run')})

test('driver discovers newest exact terminal predecessor by run_id and carries only verified repair lineage',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const make=(runId,condition,{repair=false,quarantine=false}={})=>{const w=new ImmutableReceiptWriter(join(root,'WT','runs',runId,'receipts'),runId);w.write('run-identity',{workload_id:'WT',predecessor_run_id:null,condition_fingerprint:condition});w.write('lineage',{workload_id:'WT',predecessor_run_id:null,condition_fingerprint:condition,reason:'initial-run'});w.write('classification',{result:'FAIL',class:'HARNESS_DEFECT',root_cause:'fixture',product_repair_authorized:false});w.write('cleanup',{quarantined:quarantine?[{kind:'process'}]:[]});w.write('summary',{status:'FAIL',workload_id:'WT',classification:'HARNESS_DEFECT'});if(repair)w.write('repair',{verified:true,repair_commit:'abc',predecessor_run_id:runId})};make('WT-2-new','cond-new',{repair:true});make('WT-1-old','cond-old',{repair:true});const p=discoverTerminalPredecessor(root,'WT');assert.equal(p.run_id,'WT-2-new');assert.equal(p.condition_fingerprint,'cond-new');assert.equal(p.repair_receipt.verified,true);assert.equal(p.repair_receipt.predecessor_run_id,'WT-2-new');const bad='WT-3-bad',w=new ImmutableReceiptWriter(join(root,'WT','runs',bad,'receipts'),bad);w.write('run-identity',{workload_id:'WT',condition_fingerprint:'bad'});w.write('lineage',{workload_id:'WT',condition_fingerprint:'bad'});w.write('classification',{result:'FAIL',class:'HARNESS_DEFECT',root_cause:'x',product_repair_authorized:false});w.write('cleanup',{quarantined:[{kind:'lock'}]});w.write('summary',{status:'FAIL',workload_id:'WT'});assert.throws(()=>discoverTerminalPredecessor(root,'WT'),/PREDECESSOR_CLEANUP_QUARANTINED/)})

test('hash-bound append-only receipt correction repairs projection without overwriting malformed immutable history',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const runId='WT-4-corrected',receiptsRoot=join(root,'WT','runs',runId,'receipts'),w=new ImmutableReceiptWriter(receiptsRoot,runId);w.write('run-identity',{workload_id:'WT',condition_fingerprint:'cond'});w.write('lineage',{workload_id:'WT',condition_fingerprint:'cond'});w.write('classification',{result:'FAIL',class:'HARNESS_DEFECT',root_cause:'x',product_repair_authorized:false});w.write('cleanup',{quarantine:[]});w.write('summary',{terminal:true,result:'FAIL'});w.write('repair',{verified:true,repair_commit:'abc'});const targets=['cleanup','summary','repair'].map(kind=>{const path=join(receiptsRoot,`${kind}.json`),body=readFileSync(path);return{kind,original_sha256:createHash('sha256').update(body).digest('hex'),patch:kind==='summary'?{status:'FAIL',workload_id:'WT'}:kind==='repair'?{predecessor_run_id:runId}:{quarantined:[]}}});writeFileSync(join(receiptsRoot,'receipt-correction.json'),JSON.stringify({schema:1,kind:'receipt-correction',run_id:runId,targets},null,2)+'\n');const before=readFileSync(join(receiptsRoot,'summary.json'),'utf8');const p=discoverTerminalPredecessor(root,'WT');assert.equal(p.run_id,runId);assert.equal(p.repair_receipt.predecessor_run_id,runId);assert.equal(readFileSync(join(receiptsRoot,'summary.json'),'utf8'),before);targets[0].original_sha256='0'.repeat(64);writeFileSync(join(receiptsRoot,'receipt-correction.json'),JSON.stringify({schema:1,kind:'receipt-correction',run_id:runId,targets},null,2)+'\n');assert.throws(()=>discoverTerminalPredecessor(root,'WT'),/RECEIPT_CORRECTION_HASH_MISMATCH/)})


test('oracle deterministic smoke compares immutable result signatures',async()=>{const fixed={exit_code:0,stdout_sha256:'a',stderr_sha256:'b',oracle_identity:'o',fixture_identity:'f'};const r=await smokeOracleDeterminism(async()=>({...fixed}));assert.equal(r.status,'PASS');let n=0;await assert.rejects(()=>smokeOracleDeterminism(async()=>({...fixed,stdout_sha256:String(++n)})),/ORACLE_NONDETERMINISTIC_SMOKE/)})

import {prepareOperatorControlRoot} from '../scripts/workload-acceptance/isolation.mjs'
test('operator control root is fixture-external and group/world inaccessible',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const fixture=join(root,'fixture');mkdirSync(fixture);const control=prepareOperatorControlRoot(join(root,'control'),fixture);assert.equal(control.mode,0o700);assert.throws(()=>prepareOperatorControlRoot(join(fixture,'control'),fixture),/CONTROL_ROOT_ISOLATION_VIOLATION/)})

test('common cleanup terminates exact owned process and releases exact owned lock only',async t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));const lock=new AuthoritativeRunLock(join(root,'owned.lock'),{workloadId:'WT',runId:'r1'});await lock.acquire();const pm=new OwnedProcessManager(root);const p=await pm.spawn({runId:'r1',workloadId:'WT',command:process.execPath,args:['-e','setInterval(()=>{},1000)'],cwd:root,readiness:{kind:'delay',ms:20}});const c=await cleanupOwnedResources('r1',[{kind:'process',ownerRunId:'r1',manager:pm,contract:p,options:{graceMs:100}},{kind:'lock',ownerRunId:'r1',lock}]);assert.equal(c.quarantined.length,0);assert.equal(c.cleaned.length,2);const contender=new AuthoritativeRunLock(join(root,'owned.lock'),{workloadId:'WT',runId:'r2'});await contender.acquire();await contender.release()})


test('common execution driver normalizes boolean-map and array model capabilities before pool selection',()=>{const rows=normalizeLiveModels([{id:'m',providerID:'p',capabilities:{input:{text:true,image:false},output:{text:true}}},{id:'n',providerID:'p',capabilities:{input:['text','image'],output:['text']},status:'active'}]);assert.deepEqual(rows,[{id:'p/m',capabilities:['text'],status:null,zeroCost:false},{id:'p/n',capabilities:['text','image'],status:'active',zeroCost:false}]);assert.deepEqual(modelIdentity('p/m'),{providerID:'p',modelID:'m'})})

test('common driver builds declared isolated model runtime environment as a pure contract',()=>{const identity={name:'node',home:'/home/node'},env=buildRuntimeEnvironment(identity,{hiState:'/run/hi',tmp:'/run/tmp'});assert.deepEqual(env,{HOME:'/home/node',USER:'node',LOGNAME:'node',OPENCODE_HI_STATE_DIR:'/run/hi',OPENCODE_EXPERIMENTAL_WORKSPACES:'true',TMPDIR:'/run/tmp',TMP:'/run/tmp',TEMP:'/run/tmp'})})

test('run-meta predecessor identity is sourced from the same discovered predecessor as immutable lineage',()=>{const src=readFileSync(new URL('../scripts/workload-acceptance/execution-driver.mjs',import.meta.url),'utf8');assert.match(src,/predecessor_run_id:predecessor\?\.run_id\?\?null/);assert.doesNotMatch(src,/predecessor_run_id:null,started_at/)})

test('W execution binds the canonical Hi working primary instead of native build fallback',()=>{const src=readFileSync(new URL('../scripts/workload-acceptance/execution-driver.mjs',import.meta.url),'utf8');assert.equal(W_PRIMARY_AGENT,'working-manager');assert.ok(src.includes('session.create({directory:fixture,agent:W_PRIMARY_AGENT'));assert.ok(src.includes('promptAsync({sessionID:parentID,directory:fixture,agent:W_PRIMARY_AGENT'))})

test('W permission policy allows bounded fixture-local bash for exact parent or owned child sessions and terminates scope escapes',()=>{const fixture='/sandbox/W01/fixture',owned={fixture,parentID:'s1',childSessionIDs:['child-1']};assert.deepEqual(classifyWPermissionRequest({sessionID:'s1',permission:'bash',metadata:{command:'node --test test/public.test.mjs'}},owned),{action:'ALLOW_ONCE',reason:'fixture-local-bash'});assert.deepEqual(classifyWPermissionRequest({sessionID:'child-1',permission:'bash',metadata:{command:'python3 -m unittest discover -s test -v'}},owned),{action:'ALLOW_ONCE',reason:'fixture-local-bash'});for(const request of [{sessionID:'s1',permission:'external_directory',patterns:['/workspace/OpenCode-Hi/scripts/*']},{sessionID:'child-1',permission:'bash',metadata:{command:'find /workspace -type f'}},{sessionID:'s1',permission:'bash',metadata:{command:'cat ../secret'}}])assert.equal(classifyWPermissionRequest(request,owned).action,'REJECT_TERMINAL');assert.equal(classifyWPermissionRequest({sessionID:'other',permission:'bash',metadata:{command:'node --test'}},owned).action,'IGNORE')})



test('exact CLI verbose model inventory parser binds announced identity to metadata',()=>{const stdout='p/m\n{\n  "id": "m",\n  "providerID": "p",\n  "status": "active",\n  "capabilities": {"input":{"text":true},"output":{"text":true}}\n}\np/n\n{\n  "id": "n",\n  "providerID": "p",\n  "capabilities": {"input":["text"],"output":["text"]}\n}\n';const rows=parseVerboseModelInventory(stdout);assert.equal(rows.length,2);assert.equal(rows[0].id,'m');assert.throws(()=>parseVerboseModelInventory(stdout.replace('"providerID": "p"','"providerID": "other"')),/MODEL_INVENTORY_ID_MISMATCH/)})

test('common execution driver terminal boundary includes waiting-user without treating it as success',()=>{assert.equal(missionTerminalStatus('completed'),true);assert.equal(missionTerminalStatus('waiting-user'),true);assert.equal(missionTerminalStatus('active'),false)})

test('common execution driver projects source plugin config as harness-owned git-excluded host state',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(join(root,'.git','info'),{recursive:true});const config=writeSourcePluginConfig(root);assert.equal(existsSync(config),true);assert.match(readFileSync(config,'utf8'),/plugin\/dist\/plugin\.js/);assert.match(readFileSync(join(root,'.git','info','exclude'),'utf8'),/opencode\.json/)})

test('common execution entrypoint is generic and binds dispatch, native sessions, liveness, oracle and exact cleanup',()=>{const src=readFileSync(new URL('../scripts/workload-acceptance/execution-driver.mjs',import.meta.url),'utf8');for(const needle of ['WorkloadAcceptanceHarness','session.create','session.promptAsync','session.children','assessHarnessLiveness','runHiddenOracle','cleanupOwnedResources'])assert.ok(src.includes(needle),needle);assert.doesNotMatch(src,/run-w0[1-9]\.sh|workloads\/W01|opencode-go\//)})


test('post-admission resource setup is inside cleanup boundary and consumes typed control handle path',()=>{const src=readFileSync(new URL('../scripts/workload-acceptance/execution-driver.mjs',import.meta.url),'utf8'),admission=src.indexOf('requireReadyAdmission(run)'),setup=src.indexOf('prepareOperatorControlRoot',admission),guard=src.indexOf('try{',admission);assert.ok(admission>=0&&setup>admission&&guard>admission);assert.ok(guard<setup,'post-lock resource setup must be inside try/catch cleanup boundary');const setupEnd=src.indexOf(String.fromCharCode(10),setup),setupLine=src.slice(setup,setupEnd);assert.match(setupLine,/prepareOperatorControlRoot\(.+\)\.path/,'typed control handle must be dereferenced to its path')})


test('canonical W01 spec resolves exact immutable seed and proves baseline before lock admission',()=>{const spec=JSON.parse(readFileSync(new URL('../.agent-work/workload-acceptance/W01/spec.json',import.meta.url),'utf8'));const resolved=resolveExecutionContract('W01',spec);assert.equal(resolved.seedIdentity,spec.fixture.baseline.value);assert.match(resolved.seed,/fixture-seed$/);assert.match(resolved.promptPath,/W01\/prompt\.txt$/);assert.match(resolved.oraclePath,/control\/W01\/oracle\.mjs$/)})

test('execution contract rejects seed drift before authoritative preflight',()=>{const spec=JSON.parse(readFileSync(new URL('../.agent-work/workload-acceptance/W01/spec.json',import.meta.url),'utf8'));assert.throws(()=>resolveExecutionContract('W01',{...spec,fixture:{...spec.fixture,baseline:{...spec.fixture.baseline,value:'deadbeef'}}}),/WORKLOAD_FIXTURE_SEED_BASELINE_MISMATCH/)})


test('operator and model runtime are OS-separated so the hidden oracle stays unreadable to model execution',t=>{if(process.platform!=='linux'||process.getuid?.()!==0)return t.skip('requires Linux root operator');const identity=resolveRuntimeIdentity('node'),spec=JSON.parse(readFileSync(new URL('../.agent-work/workload-acceptance/W01/spec.json',import.meta.url),'utf8')),resolved=resolveExecutionContract('W01',spec);assert.equal(assertOperatorRuntimeSeparation(resolved.oraclePath,identity),true)})

test('owned process identity binds and executes under the declared uid/gid',async t=>{if(process.platform!=='linux'||process.getuid?.()!==0)return t.skip('requires Linux root operator');const identity=resolveRuntimeIdentity('node'),root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));chmodSync(root,0o755);const pm=new OwnedProcessManager(root),p=await pm.spawn({runId:'r-uid',workloadId:'WT',command:process.execPath,args:['-e','setInterval(()=>{},1000)'],cwd:root,uid:identity.uid,gid:identity.gid,readiness:{kind:'delay',ms:30}});const status=readFileSync(`/proc/${p.pid}/status`,'utf8'),uid=Number(/^Uid:\s+(\d+)/m.exec(status)?.[1]),gid=Number(/^Gid:\s+(\d+)/m.exec(status)?.[1]);assert.equal(uid,identity.uid);assert.equal(gid,identity.gid);assert.equal(p.uid,identity.uid);assert.equal(p.gid,identity.gid);const x=await pm.terminate(p,{graceMs:100});assert.equal(x.signalled,true)})

test('canonical W prompt catalog contains exactly W01-W18 and each materialized prompt is byte-exact',()=>{
  const canonical=parseCanonicalPromptCatalog();assert.equal(Object.keys(canonical.prompts).length,18);assert.deepEqual(Object.keys(canonical.prompts).sort(),WORKLOAD_IDS)
  for(const id of WORKLOAD_IDS){const p=readFileSync(new URL(`../.agent-work/workload-acceptance/${id}/prompt.txt`,import.meta.url),'utf8');assert.equal(p,canonical.prompts[id],id)}
})

test('immutable W catalog binds 18 specs, seeds, prompts and hidden oracle identities',()=>{
  const catalog=buildCatalogManifest();assert.equal(catalog.entry_count,18);assert.deepEqual(Object.keys(catalog.entries).sort(),WORKLOAD_IDS)
  for(const id of WORKLOAD_IDS){const e=resolveCatalogEntry(id,{catalog});assert.equal(e.id,id);assert.match(e.prompt_sha256,/^[a-f0-9]{64}$/);assert.match(e.fixture_sha256,/^[a-f0-9]{64}$/);assert.match(e.oracle_identity,/^[a-f0-9]{64}$/)}
})

test('generic executor has no W-specific execution branch and accepts the full catalog ID domain',()=>{
  const entry=readFileSync(new URL('../scripts/workload-acceptance/execute.mjs',import.meta.url),'utf8'),driver=readFileSync(new URL('../scripts/workload-acceptance/execution-driver.mjs',import.meta.url),'utf8')
  assert.match(entry,/W\(\?:0\[1-9\]\|1\[0-8\]\)/);assert.match(driver,/resolveCatalogEntry\(workloadId\)/)
  assert.doesNotMatch(driver,/if\s*\([^\n)]*workloadId[^\n)]*===\s*['"]W\d\d/);assert.doesNotMatch(driver,/switch\s*\(\s*workloadId\s*\)/);assert.doesNotMatch(driver,/run-w\d\d/i)
})

test('configured W model preference set remains exactly ten entries and is test-only data',()=>{
  const p=JSON.parse(readFileSync(new URL('../.agent-work/workload-acceptance/model-pool.json',import.meta.url),'utf8'));assert.equal(p.scope,'w-development-test-only');assert.equal(p.models.length,10);assert.equal(new Set(p.models.map(x=>x.id)).size,10)
})

test('catalog certification treats known-broken concurrency baseline as deterministic when FAIL verdict is stable even if failed-check manifestation varies',()=>{
  const observations=[{status:1,passed:2,failed:2,total:4,verdict:'FAIL'},{status:1,passed:1,failed:3,total:4,verdict:'FAIL'}]
  assert.equal(new Set(observations.map(x=>x.verdict)).size,1)
  assert.equal(observations.every(x=>x.failed>0),true)
  assert.notEqual(observations[0].failed,observations[1].failed)
})


test('W child model confinement uses only live canonical W pool members',()=>{const pool=[{id:'p/a'},{id:'p/b'},{id:'p/offline'}],live=[{id:'p/a'},{id:'p/b'},{id:'p/other'}];assert.deepEqual(effectiveWModelIds(pool,live),['p/a','p/b'])})

test('W run writes an adaptive project-local strict child allowlist without changing global product routing',t=>{const root=temp();t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(join(root,'.git','info'),{recursive:true});writeSourcePluginConfig(root);const r=writeWModelConfinement(root,['p/a','p/b','p/a']);const doc=JSON.parse(readFileSync(r.path,'utf8'));assert.equal(doc.execution.topology,'adaptive');assert.deepEqual(doc.routing.allowedModels,['p/a','p/b']);assert.match(readFileSync(join(root,'.git','info','exclude'),'utf8'),/\.opencode\//)})

test('W run detects any child model or host-default escape outside the confined pool',()=>{const mission={execution:{workers:[{id:'w1',task_id:'t1',role:'coder',model:'p/a'},{id:'w2',task_id:'t2',role:'test-engineer',model:'p/paid'},{id:'w3',task_id:'t3',role:'qa-reviewer',model:'host-default'}]}};assert.deepEqual(outOfPoolWorkerModels(mission,['p/a']),[{worker_id:'w2',task_id:'t2',role:'test-engineer',model:'p/paid'},{worker_id:'w3',task_id:'t3',role:'qa-reviewer',model:'host-default'}])})
