import { createHash } from 'node:crypto'
import type { Category,ExecutionProfile,MethodologyProvenance,MissionState,MissionTask,WorkerResult,WorkerState } from '../mission/types.js'
import { bindContextReference,type ContextReferenceDraft } from '../../contracts/context-reference.js'
import { appendLedger } from '../ledger/ledger.js'
function uid(prefix:string):string{return`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function canon(items:string[]=[]):string{return[...new Set(items.map(x=>x.trim().replace(/\\/g,'/').replace(/\/+$/,'')).filter(Boolean))].sort().join(',')}
export function workerFingerprint(role:string,category:Category,model:string|undefined,taskFamily:string,objective='',contract?:{scope?:string[];constraints?:string[];dependencies?:string[];requiredEvidence?:string[];obligationIds?:string[]}):string{return[role,category,model??'default',taskFamily,objective.trim().toLowerCase().replace(/\s+/g,' ').slice(0,240),`scope:${canon(contract?.scope)}`,`constraints:${canon(contract?.constraints)}`,`deps:${canon(contract?.dependencies)}`,`evidence:${canon(contract?.requiredEvidence)}`,`obligations:${canon(contract?.obligationIds)}`].join('|')}
export function createTask(m:MissionState,input:{objective:string;role:string;category:Category;scope?:string[];constraints?:string[];dependencies?:string[];requiredEvidence?:string[];obligationIds?:string[];contextReferences?:ContextReferenceDraft[];verificationCases?:import('../../contracts/verification-case.js').VerificationCase[];executionProfile?:ExecutionProfile}):MissionTask{const now=Date.now(),id=uid('t'),task:MissionTask={id,mission_id:m.identity.mission_id,objective:input.objective,status:'created',role:input.role,category:input.category,scope:input.scope??[],constraints:input.constraints??[],dependencies:input.dependencies??[],requiredEvidence:input.requiredEvidence??[],...(input.verificationCases?.length?{verification_cases:input.verificationCases.map(c=>({...c,required_browser_actions:[...c.required_browser_actions]}))}:{}),obligation_ids:[...new Set(input.obligationIds??[])],context_artifacts:(input.contextReferences??[]).map(ref=>bindContextReference(ref,id)),execution_profile:input.executionProfile,gate_ids:[],external_action_requirements:[...m.identity.intent.requestedExternalActions],created_at:now,updated_at:now};m.execution.tasks.push(task);appendLedger(m,'task.created',{task_id:task.id,payload:{role:task.role,category:task.category,dependencies:task.dependencies,obligation_ids:task.obligation_ids}});return task}
export function createWorker(m:MissionState,task:MissionTask,model?:string,fallbacks:string[]=[],selectedMethodologies:string[]=[],methodologyProvenanceItems:MethodologyProvenance[]=[]):WorkerState{const now=Date.now(),w:WorkerState={id:uid('w'),task_id:task.id,role:task.role,category:task.category,parent_session_id:m.identity.session_id,parent_mission_id:m.identity.mission_id,model,fallbacks,selected_methodologies:selectedMethodologies,loaded_methodologies:[],methodologies:methodologyProvenanceItems,fingerprint:workerFingerprint(task.role,task.category,model,m.identity.intent.taskKind,task.objective,{scope:task.scope,constraints:task.constraints,dependencies:task.dependencies,requiredEvidence:task.requiredEvidence,obligationIds:task.obligation_ids}),status:'created',attempt:0,generation_at_spawn:m.continuation.generation,updated_at:now};m.execution.workers.push(w);task.worker_id=w.id;appendLedger(m,'worker.created',{task_id:task.id,worker_id:w.id,payload:{model,selected_methodologies:selectedMethodologies,generation:m.continuation.generation,mission_id:m.identity.mission_id,methodologies:methodologyProvenanceItems.map(x=>({name:x.name,provider:x.provider,permission:x.permission,injection:x.injection,sha256:x.source_sha256}))}});return w}
export function workerAttemptPromptMessageID(worker:WorkerState,at:number):string{const stamp=Number.isFinite(at)&&at>=0?Math.floor(at):Date.now(),ordinal=Math.max(0,Math.floor(worker.attempt??0)),tick=(BigInt(stamp)*0x1000n+BigInt(ordinal&0xfff))&0xffffffffffffn,time=tick.toString(16).padStart(12,'0'),entropy=createHash('sha256').update([worker.parent_mission_id,worker.task_id,worker.id,worker.session_id??'session-pending',String(worker.generation_at_spawn),String(ordinal),String(stamp)].join('\0')).digest('hex').slice(0,14);return`msg_${time}${entropy}`}
export function beginWorkerAttempt(task:MissionTask,worker:WorkerState,at=Date.now()):void{worker.attempt=(worker.attempt??0)+1;worker.started_at=at;delete worker.last_result_digest;delete worker.last_result_at;delete worker.pending_native_permission_denial;worker.attempt_prompt_message_id=workerAttemptPromptMessageID(worker,at);worker.updated_at=at;task.updated_at=at}
export function retireTaskResultIssues(m:MissionState,taskID:string,issues:string[],replacementIssues:string[]=[]):string[]{
  if(!issues.length)return[]
  const replacement=new Set(replacementIssues),stillOwned=new Set(m.execution.tasks.filter(t=>t.id!==taskID&&t.status!=='cancelled'&&t.result?.status!=='DONE').flatMap(t=>t.result?.open_issues??[])),retired=issues.filter(issue=>!replacement.has(issue)&&!stillOwned.has(issue))
  if(retired.length)m.execution.blockers=m.execution.blockers.filter(blocker=>!retired.includes(blocker))
  return retired
}
export function applyWorkerResult(m:MissionState,task:MissionTask,worker:WorkerState,result:WorkerResult):void{const supersededIssues=[...(task.result?.open_issues??[])];task.result=result;task.updated_at=Date.now();worker.completed_at=task.updated_at;worker.updated_at=task.updated_at;if(result.status==='DONE'){task.status='completed';worker.status='completed'}else if(result.status==='BLOCKED'||result.status==='NEEDS_CONTEXT'){task.status='blocked';worker.status='ready'}else if(result.status==='FIX_REQUIRED'){task.status='waiting';worker.status='ready'}else{task.status='failed';worker.status='failed'}m.vcs.changed_files=[...new Set([...m.vcs.changed_files,...result.changed_files])];retireTaskResultIssues(m,task.id,supersededIssues,result.open_issues);if(result.status!=='DONE')m.execution.blockers=[...new Set([...m.execution.blockers,...result.open_issues])];appendLedger(m,'worker.completed',{task_id:task.id,worker_id:worker.id,payload:{status:result.status,changed_files:result.changed_files}})}
