import type { Category,ExecutionProfile,MethodologyProvenance,MissionState,MissionTask,WorkerResult,WorkerState } from '../mission/types.js'
import { bindContextReference,type ContextReferenceDraft } from '../../contracts/context-reference.js'
import { appendLedger } from '../ledger/ledger.js'
function uid(prefix:string):string{return`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function canon(items:string[]=[]):string{return[...new Set(items.map(x=>x.trim().replace(/\\/g,'/').replace(/\/+$/,'')).filter(Boolean))].sort().join(',')}
export function workerFingerprint(role:string,category:Category,model:string|undefined,taskFamily:string,objective='',contract?:{scope?:string[];constraints?:string[];dependencies?:string[];requiredEvidence?:string[];obligationIds?:string[]}):string{return[role,category,model??'default',taskFamily,objective.trim().toLowerCase().replace(/\s+/g,' ').slice(0,240),`scope:${canon(contract?.scope)}`,`constraints:${canon(contract?.constraints)}`,`deps:${canon(contract?.dependencies)}`,`evidence:${canon(contract?.requiredEvidence)}`,`obligations:${canon(contract?.obligationIds)}`].join('|')}
export function createTask(m:MissionState,input:{objective:string;role:string;category:Category;scope?:string[];constraints?:string[];dependencies?:string[];requiredEvidence?:string[];obligationIds?:string[];contextReferences?:ContextReferenceDraft[];executionProfile?:ExecutionProfile}):MissionTask{const now=Date.now(),id=uid('t'),task:MissionTask={id,mission_id:m.mission_id,objective:input.objective,status:'created',role:input.role,category:input.category,scope:input.scope??[],constraints:input.constraints??[],dependencies:input.dependencies??[],requiredEvidence:input.requiredEvidence??[],obligation_ids:[...new Set(input.obligationIds??[])],context_artifacts:(input.contextReferences??[]).map(ref=>bindContextReference(ref,id)),execution_profile:input.executionProfile,gate_ids:[],external_action_requirements:[...m.intent.requestedExternalActions],created_at:now,updated_at:now};m.tasks.push(task);appendLedger(m,'task.created',{task_id:task.id,payload:{role:task.role,category:task.category,dependencies:task.dependencies,obligation_ids:task.obligation_ids}});return task}
export function createWorker(m:MissionState,task:MissionTask,model?:string,fallbacks:string[]=[],selectedMethodologies:string[]=[],methodologyProvenanceItems:MethodologyProvenance[]=[]):WorkerState{const now=Date.now(),w:WorkerState={id:uid('w'),task_id:task.id,role:task.role,category:task.category,parent_session_id:m.session_id,parent_mission_id:m.mission_id,model,fallbacks,selected_methodologies:selectedMethodologies,loaded_methodologies:[],methodologies:methodologyProvenanceItems,fingerprint:workerFingerprint(task.role,task.category,model,m.intent.taskKind,task.objective,{scope:task.scope,constraints:task.constraints,dependencies:task.dependencies,requiredEvidence:task.requiredEvidence,obligationIds:task.obligation_ids}),status:'created',attempt:0,generation_at_spawn:m.generation,updated_at:now};m.workers.push(w);task.worker_id=w.id;appendLedger(m,'worker.created',{task_id:task.id,worker_id:w.id,payload:{model,selected_methodologies:selectedMethodologies,generation:m.generation,mission_id:m.mission_id,methodologies:methodologyProvenanceItems.map(x=>({name:x.name,provider:x.provider,permission:x.permission,injection:x.injection,sha256:x.source_sha256}))}});return w}
export function beginWorkerAttempt(task:MissionTask,worker:WorkerState,at=Date.now()):void{worker.attempt+=1;worker.started_at=at;worker.updated_at=at;task.updated_at=at}
export function applyWorkerResult(m:MissionState,task:MissionTask,worker:WorkerState,result:WorkerResult):void{task.result=result;task.updated_at=Date.now();worker.completed_at=task.updated_at;worker.updated_at=task.updated_at;if(result.status==='DONE'){task.status='completed';worker.status='completed'}else if(result.status==='BLOCKED'||result.status==='NEEDS_CONTEXT'){task.status='blocked';worker.status='ready'}else if(result.status==='FIX_REQUIRED'){task.status='waiting';worker.status='ready'}else{task.status='failed';worker.status='failed'}m.changed_files=[...new Set([...m.changed_files,...result.changed_files])];m.blockers=[...new Set([...m.blockers,...result.open_issues])];appendLedger(m,'worker.completed',{task_id:task.id,worker_id:worker.id,payload:{status:result.status,changed_files:result.changed_files}})}
