import {spawn} from 'node:child_process'
import {createHash} from 'node:crypto'
import {mkdirSync,openSync,closeSync} from 'node:fs'
import {join} from 'node:path'
const hash=(command,args,cwd)=>createHash('sha256').update([command,cwd,...args].join('\0')).digest('hex')
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
async function waitReady(record,readiness){if(readiness.kind==='delay'){await sleep(Math.max(0,readiness.ms??0));return true}if(readiness.kind==='probe'){const deadline=Date.now()+Math.max(1,readiness.timeoutMs??5000),interval=Math.max(5,readiness.intervalMs??50);while(Date.now()<deadline){if(await readiness.probe(record))return true;await sleep(interval)}return false}throw new Error(`READINESS_KIND_UNSUPPORTED:${readiness.kind}`)}
export class OwnedProcessManager{
  #records=new Map()
  constructor(root){this.root=root;mkdirSync(root,{recursive:true})}
  async spawn({runId,workloadId,command,args=[],cwd,env={},readiness={kind:'delay',ms:25}}){const logDir=join(this.root,'process-logs',runId);mkdirSync(logDir,{recursive:true});const out=openSync(join(logDir,`${Date.now()}-stdout.log`),'a'),err=openSync(join(logDir,`${Date.now()}-stderr.log`),'a');const child=spawn(command,args,{cwd,env:{...process.env,...env},detached:true,stdio:['ignore',out,err]});closeSync(out);closeSync(err);const record={schema:1,run_id:runId,workload_id:workloadId,pid:child.pid,pgid:child.pid,command,cwd,args:[...args],command_identity:hash(command,args,cwd),status:'RUNNING'};this.#records.set(child.pid,record);child.once('exit',(code,signal)=>{const r=this.#records.get(child.pid);if(r)Object.assign(r,{status:'EXITED',exit_code:code,exit_signal:signal})});const ready=await waitReady(record,readiness);if(!ready||child.exitCode!==null){try{process.kill(-record.pgid,'SIGTERM')}catch{};throw new Error(`PROCESS_READINESS_FAILED:${child.exitCode??'probe-timeout'}`)}return structuredClone(record)}
  async terminate(record,{graceMs=250}={}){const owned=this.#records.get(record.pid);if(!owned||owned.run_id!==record.run_id||owned.workload_id!==record.workload_id||owned.command_identity!==record.command_identity||owned.pgid!==record.pgid)return{disposition:'QUARANTINED',signalled:false,reason:'PROCESS_OWNER_MISMATCH'};if(owned.status!=='RUNNING')return{disposition:'ALREADY_TERMINAL',signalled:false};try{process.kill(-owned.pgid,'SIGTERM')}catch(e){return{disposition:'QUARANTINED',signalled:false,reason:`TERM_FAILED:${e.code??e}`}};for(let n=0;n<Math.max(1,Math.ceil(graceMs/25));n++){await sleep(25);if(owned.status!=='RUNNING')return{disposition:'TERMINATED',signalled:true,signal:'SIGTERM'}}try{process.kill(-owned.pgid,'SIGKILL')}catch(e){return{disposition:'QUARANTINED',signalled:true,reason:`KILL_FAILED:${e.code??e}`}};return{disposition:'TERMINATED',signalled:true,signal:'SIGKILL'}}
}
