import { assessedIntent, provisionalIntent, type SemanticIntentAssessment } from '../intent/semantic-assessment.js'
import { collectRepoContext, type RepoContext, type NativeProjectContext } from '../intent/repo-context.js'
import { continuationBudget, resolveCategory } from '../routing/category.js'
import { appendLedger } from '../ledger/ledger.js'
import { verificationPolicyFor } from '../verification/policy.js'
import { syncMissionGates } from '../gates/gates.js'
import { minimumTeamFor } from '../routing/minimum-team.js'
import { decideAdaptiveExecution } from '../execution/adaptive-policy.js'
import { decideTopology, type TopologyPolicyConfig } from '../execution/topology-policy.js'
import { activateMethodologySignal, suppressIntentMethodologySignals } from '../methodology/activation.js'
import { architectureMethodologySignals } from '../methodology/signals.js'
import type { MissionState, Obligation } from './types.js'
function obligation(id:string,kind:Obligation['kind'],summary:string,requiredEvidence:string[]=[]):Obligation{return{id,kind,summary,status:'open',requiredEvidence}}
export class MissionStore {
  readonly #bySession=new Map<string,MissionState>();readonly #root:string;readonly #repo:RepoContext;readonly #getPrimaryMode:()=> 'auto'|'working-manager'|'manager';readonly #getTopology:()=>TopologyPolicyConfig
  constructor(root=process.cwd(),nativeContext:NativeProjectContext={},getPrimaryMode:()=> 'auto'|'working-manager'|'manager'=()=> 'auto',getTopology:()=>TopologyPolicyConfig=()=>({mode:'adaptive',maxAgents:4,parallelism:2})){this.#root=root;this.#repo=collectRepoContext(root,nativeContext);this.#getPrimaryMode=getPrimaryMode;this.#getTopology=getTopology}
  start(sessionID:string,userText:string,observedPrimary?:MissionState['primary_mode']):MissionState{
    const intent=provisionalIntent(userText,this.#repo),now=Date.now(),primaryConfigured=this.#getPrimaryMode(),primary:MissionState['primary_mode']=observedPrimary??(primaryConfigured==='manager'?'manager':'working-manager')
    const mission:MissionState={mission_id:`m_${now.toString(36)}_${Math.random().toString(36).slice(2,10)}`,session_id:sessionID,objective:intent.objective,intent,semantic_assessment:{status:'pending',phase:'initial',revision:1,source:'host-primary',pending_text:userText.slice(0,12000)},status:'active',risk:intent.risk,execution_mode:'single',primary_mode:primary,verification_policy:{requiredKinds:[],requireFresh:true,requireReview:false,allowWorkerReportedEvidence:true},adaptive_execution:{path:'DIRECT',reasons:['semantic assessment pending']},topology:{mode:'single-agent',parallelism:1,reason:['semantic assessment pending']},generation:1,iteration:0,continuation_budget:continuationBudget('standard'),continuation_active:false,obligations:[],tasks:[],workers:[],evidence:{fresh:false,items:[]},ledger:[],changed_files:[],blockers:[],constraints:[],native_todos_incomplete:0,last_progress_signature:'',stagnation_count:0,context_artifacts:[],gates:[],temporary_mutations:[],methodology_needs:[],parent_loaded_methodologies:[],pending_permissions:0,pending_permission_ids:[],user_interrupted:false,resume_count:0,last_user_message_at:now,created_at:now,updated_at:now}
    syncMissionGates(mission);appendLedger(mission,'mission.provisional',{payload:{semantic_revision:1,technical_targets:intent.likelyTargets??[],repo:{name:this.#repo.name,ecosystems:this.#repo.ecosystems,markers:this.#repo.markers,native:this.#repo.native}}});mission.last_progress_signature=this.signature(mission);this.#bySession.set(sessionID,mission);return mission
  }
  applyInitialSemanticAssessment(sessionID:string,assessment:SemanticIntentAssessment):MissionState{
    const m=this.get(sessionID);if(!m)throw new Error('No active Hi mission')
    if(m.semantic_assessment.status!=='pending'||m.semantic_assessment.phase!=='initial')throw new Error('Hi semantic assessment is not pending for initial mission')
    if(!['mission','non-material'].includes(assessment.message_kind))throw new Error('Initial semantic assessment requires message_kind=mission or non-material')
    const now=Date.now();m.semantic_assessment.status='assessed';m.semantic_assessment.assessed_at=now
    if(!assessment.material){m.status='completed';m.obligations=[];m.methodology_needs=[];appendLedger(m,'semantic.non-material',{payload:{revision:m.semantic_assessment.revision,source:m.semantic_assessment.source}});syncMissionGates(m);m.updated_at=now;m.last_progress_signature=this.signature(m);return m}
    m.intent=assessedIntent(m.intent,assessment);m.risk=m.intent.risk;m.objective=m.intent.objective
    const obligations:Obligation[]=[]
    if(m.intent.taskKind==='bug-fix'||m.intent.taskKind==='performance')obligations.push(obligation('o-analysis','analysis',m.intent.taskKind==='bug-fix'?'Root cause understood':'Relevant performance bottleneck identified'))
    if(m.intent.taskKind!=='review'&&m.intent.taskKind!=='release-readiness')obligations.push(obligation('o-implementation','implementation','Requested change completed'))
    if(m.intent.taskKind==='review')obligations.push(obligation('o-review','review','Requested review completed',m.intent.likelyVerification))
    obligations.push(obligation('o-verification','verification',m.intent.likelyVerification.join(', '),m.intent.likelyVerification))
    if(m.intent.risk==='high')obligations.push(obligation('o-high-assurance','review','Security-sensitive change reviewed'))
    if(m.intent.risk==='authority-boundary')obligations.push(obligation('o-authority','authority','External action explicitly authorized and completed'))
    m.obligations=obligations
    m.verification_policy=verificationPolicyFor(m.intent)
    const category=resolveCategory(m.intent),team=minimumTeamFor(m.intent,m.verification_policy,m.primary_mode),adaptive=decideAdaptiveExecution(m.intent),topology=decideTopology(m.intent,this.#getTopology())
    m.execution_mode=topology.executionMode;m.primary_mode=team.primary;m.adaptive_execution={path:adaptive.path,reasons:adaptive.reasons};m.topology={mode:topology.mode,parallelism:topology.parallelism,reason:topology.reason};m.continuation_budget=continuationBudget(category)
    m.methodology_needs=[]
    const suppressed=new Set(assessment.suppressed_intent_signals)
    for(const signal of assessment.intent_signals)if(!suppressed.has(signal))activateMethodologySignal(m,this.#root,{signal,producer:'intent',reason:'Host primary semantic assessment reported this explicit intent signal.'})
    for(const signal of architectureMethodologySignals(m.intent))activateMethodologySignal(m,this.#root,{signal:signal.name,producer:'architecture',reason:signal.reason})
    syncMissionGates(m);appendLedger(m,'semantic.assessed',{payload:{revision:m.semantic_assessment.revision,source:m.semantic_assessment.source,taskKind:m.intent.taskKind,scope:m.intent.scope,risk:m.intent.risk,ambiguity:m.intent.ambiguity,dependencyClass:m.intent.dependencyClass,capabilities:m.intent.requiredCapabilities,intent_signals:assessment.intent_signals,suppressed_intent_signals:assessment.suppressed_intent_signals,technical_targets:m.intent.likelyTargets??[]}});m.updated_at=now;m.last_progress_signature=this.signature(m);return m
  }
  bindObservedPrimary(sessionID:string,primary:MissionState['primary_mode']):void{const m=this.get(sessionID);if(!m||m.primary_mode===primary)return;const previous=m.primary_mode;m.primary_mode=primary;appendLedger(m,'primary.agent-observed',{payload:{previous,observed:primary,source:'host-chat-message'}});m.last_progress_signature=this.signature(m)}
  get(sessionID:string):MissionState|undefined{return this.#bySession.get(sessionID)}
  beginFollowupSemanticAssessment(sessionID:string,userText:string):MissionState{
    const m=this.get(sessionID);if(!m)throw new Error('No active Hi mission')
    if(!['active','waiting-user'].includes(m.status))throw new Error('Hi follow-up semantic assessment requires an active/waiting mission')
    const text=userText.trim();if(!text)throw new Error('Empty follow-up cannot be assessed')
    m.generation+=1;m.semantic_assessment={status:'pending',phase:'followup',revision:m.semantic_assessment.revision+1,source:'host-primary',pending_text:text.slice(0,12000)};m.status='active';m.continuation_active=false;m.active_action_id=undefined;m.continuation_lock_until=undefined;m.suppress_until=undefined;m.pending_nudge=undefined;m.last_user_message_at=Date.now()
    appendLedger(m,'semantic.followup-pending',{payload:{revision:m.semantic_assessment.revision,generation:m.generation,preview:text.slice(0,180)}});syncMissionGates(m);m.updated_at=Date.now();m.last_progress_signature=this.signature(m);return m
  }
  applyFollowupSemanticAssessment(sessionID:string,assessment:SemanticIntentAssessment):MissionState{
    const m=this.get(sessionID);if(!m)throw new Error('No active Hi mission')
    if(m.semantic_assessment.status!=='pending'||m.semantic_assessment.phase!=='followup')throw new Error('Hi semantic assessment is not pending for a follow-up')
    if(assessment.message_kind==='mission')throw new Error('A follow-up assessment cannot use message_kind=mission')
    const text=m.semantic_assessment.pending_text,now=Date.now();m.semantic_assessment.status='assessed';m.semantic_assessment.assessed_at=now
    if(assessment.message_kind==='non-material'){appendLedger(m,'semantic.followup-non-material',{payload:{revision:m.semantic_assessment.revision}});syncMissionGates(m);m.updated_at=now;m.last_progress_signature=this.signature(m);return m}
    if(assessment.message_kind==='stop'){m.user_interrupted=true;m.interrupted_at=now;m.interrupted_reason='semantic-user-stop';m.status='stopped';appendLedger(m,'mission.stopped',{payload:{reason:'semantic-user-stop',generation:m.generation}});syncMissionGates(m);m.updated_at=now;m.last_progress_signature=this.signature(m);return m}
    if(assessment.message_kind==='resume'){m.user_interrupted=false;m.interrupted_reason=undefined;m.resumed_at=now;m.status='active';appendLedger(m,'mission.resumed',{payload:{reason:'semantic-user-resume',generation:m.generation}});syncMissionGates(m);m.updated_at=now;m.last_progress_signature=this.signature(m);return m}
    const kind=assessment.message_kind
    if(kind==='constraint'){m.constraints??=[];if(!m.constraints.includes(text))m.constraints.push(text);m.objective=`${m.objective}\nConstraint: ${text}`.slice(0,9000);for(const task of m.tasks.filter(t=>!['completed','failed','cancelled'].includes(t.status))){task.constraints??=[];if(!task.constraints.includes(text))task.constraints.push(text);task.updated_at=now}}
    else if(kind==='verification'){m.objective=`${m.objective}\nFollow-up verification: ${text}`.slice(0,9000);let verify=m.obligations.find(o=>o.kind==='verification');if(!verify){verify=obligation('o-followup-verification-r'+m.semantic_assessment.revision,'verification',`User verification follow-up: ${text.slice(0,500)}`,assessment.likely_verification);m.obligations.push(verify)}else{verify.status='open';verify.closedAt=undefined;verify.summary=`${verify.summary}; ${text.slice(0,300)}`.slice(0,700)}}
    else{m.objective=`${m.objective}\nFollow-up: ${text}`.slice(0,9000);m.obligations.push(obligation('o-followup-r'+m.semantic_assessment.revision,'implementation',`User follow-up: ${text.slice(0,500)}`))}
    m.intent=assessedIntent(m.intent,assessment);m.intent.objective=m.objective;m.risk=m.intent.risk
    const suppressed=new Set(assessment.suppressed_intent_signals);if(suppressed.size)suppressIntentMethodologySignals(m,[...suppressed],`Host primary semantic follow-up explicitly superseded intent methodology at revision ${m.semantic_assessment.revision}.`)
    for(const signal of assessment.intent_signals)if(!suppressed.has(signal))activateMethodologySignal(m,this.#root,{signal,producer:'intent',reason:`Host primary semantic follow-up assessment revision ${m.semantic_assessment.revision}.`})
    if(m.intent.risk==='high'&&!m.obligations.some(o=>o.id==='o-high-assurance'&&o.status==='open'))m.obligations.push(obligation('o-high-assurance','review','Security-sensitive change reviewed'))
    if(m.intent.risk==='authority-boundary'&&!m.obligations.some(o=>o.kind==='authority'&&o.status==='open'))m.obligations.push(obligation(`o-authority-${now.toString(36)}`,'authority','External action explicitly authorized and completed'))
    m.verification_policy=verificationPolicyFor(m.intent);for(const signal of architectureMethodologySignals(m.intent))activateMethodologySignal(m,this.#root,{signal:signal.name,producer:'architecture',reason:signal.reason})
    const category=resolveCategory(m.intent),team=minimumTeamFor(m.intent,m.verification_policy,m.primary_mode),adaptive=decideAdaptiveExecution(m.intent,m),topology=decideTopology(m.intent,this.#getTopology(),m);m.execution_mode=topology.executionMode;m.primary_mode=team.primary;m.adaptive_execution={path:adaptive.path,reasons:adaptive.reasons};m.topology={mode:topology.mode,parallelism:topology.parallelism,reason:topology.reason};m.continuation_budget=Math.max(m.continuation_budget,continuationBudget(category));m.status='active'
    appendLedger(m,'semantic.followup-assessed',{payload:{revision:m.semantic_assessment.revision,message_kind:kind,taskKind:m.intent.taskKind,scope:m.intent.scope,risk:m.intent.risk,ambiguity:m.intent.ambiguity,dependencyClass:m.intent.dependencyClass,intent_signals:assessment.intent_signals,suppressed_intent_signals:assessment.suppressed_intent_signals}});syncMissionGates(m);m.updated_at=now;m.last_progress_signature=this.signature(m);return m
  }
  restore(missions:MissionState[],uncleanShutdown=false):void{for(const m of missions){m.continuation_active=false;m.active_action_id=undefined;m.continuation_failure_count=0;m.last_continuation_failure_at=undefined;m.suppress_until=undefined;if(m.status==='active'){const restoredTeam=m.execution_mode==='team';if(restoredTeam)m.execution_mode='single';const now=Date.now();for(const w of m.workers){if(['created','queued','starting','busy'].includes(w.status)){const t=m.tasks.find(x=>x.id===w.task_id);if(w.session_id){w.status='ready';w.restart_reconcile_pending=true;w.generation_at_spawn=m.generation;if(t&&!t.result){t.status='waiting';t.result={status:'NEEDS_CONTEXT',summary:'Runtime restarted while this worker was in flight; reconcile the existing child session before continuing.',changed_files:[],evidence:[],open_issues:[],needs_context:['runtime-restart-reconcile']}}else if(t&&['queued','running'].includes(t.status))t.status=t.result?.status==='DONE'?'completed':'waiting'}else{w.status='failed';w.completed_at=now;if(t){t.status='blocked';if(!t.result)t.result={status:'BLOCKED',summary:'Runtime restarted before a native child session was established; create a fresh bounded worker for this task.',changed_files:[],evidence:[],open_issues:[],needs_context:['runtime-restart-fresh-worker']}}}}}for(const t of m.tasks)if(['queued','running'].includes(t.status))t.status=t.result?.status==='DONE'?'completed':t.result?'waiting':'blocked';m.continuation_lock_until=undefined;if(uncleanShutdown){const pendingBefore=m.pending_permissions;m.pending_permissions=0;m.pending_permission_ids=[];if(pendingBefore>0)appendLedger(m,'permission.crash-reset',{payload:{cleared:pendingBefore,reason:'permission requests are process-ephemeral and must be re-established'}});let invalidated=0;for(const e of m.evidence.items){if(!e.invalidated_at){e.invalidated_at=now;invalidated++}}if(invalidated){m.evidence.fresh=false;appendLedger(m,'evidence.crash-invalidated',{payload:{count:invalidated,reason:'source/runtime state identity must be revalidated after unclean restart'}})}}}syncMissionGates(m);m.updated_at=Date.now();m.last_progress_signature=this.signature(m);this.#bySession.set(m.session_id,m);appendLedger(m,'mission.restored',{payload:{status:m.status,recovery:uncleanShutdown?'unclean-shutdown':'normal-restart',generation:m.generation,team_runtime:'ephemeral-reset-to-single-if-needed'}});if(uncleanShutdown)appendLedger(m,'runtime.crash-recovery',{payload:{action:'ephemeral-workers-reconciled'}})}}
  remove(sessionID:string):void{this.#bySession.delete(sessionID)}
  stop(sessionID:string,reason='user-stop'):void{const m=this.get(sessionID);if(!m)return;m.generation+=1;m.user_interrupted=true;m.interrupted_at=Date.now();m.interrupted_reason=reason;m.status='stopped';m.continuation_active=false;m.active_action_id=undefined;m.continuation_lock_until=undefined;m.suppress_until=undefined;m.pending_nudge=undefined;appendLedger(m,'mission.stopped',{payload:{reason,generation:m.generation}});syncMissionGates(m)}
  noteUserMessage(sessionID:string):void{const m=this.get(sessionID);if(!m)return;m.last_user_message_at=Date.now()}
  resume(sessionID:string,reason='explicit-user-resume'):void{const m=this.get(sessionID);if(!m)return;const wasInterrupted=m.user_interrupted||m.status==='stopped';m.generation+=1;m.user_interrupted=false;m.interrupted_reason=undefined;m.resumed_at=Date.now();m.resume_count=(m.resume_count??0)+(wasInterrupted?1:0);m.continuation_active=false;m.active_action_id=undefined;m.continuation_lock_until=undefined;m.suppress_until=undefined;m.pending_nudge=undefined;if(['stopped','waiting-user'].includes(m.status))m.status='active';appendLedger(m,'mission.resumed',{payload:{reason,resume_count:m.resume_count,generation:m.generation}});syncMissionGates(m)}
  complete(sessionID:string):void{const m=this.get(sessionID);if(!m)return;m.status='completed';syncMissionGates(m);appendLedger(m,'mission.completed')}
  all():MissionState[]{return[...this.#bySession.values()]}
  updateProgress(m:MissionState,countStagnation=false):boolean{syncMissionGates(m);const next=this.signature(m),progressed=next!==m.last_progress_signature;if(progressed)m.stagnation_count=0;else if(countStagnation)m.stagnation_count+=1;m.last_progress_signature=next;m.updated_at=Date.now();return progressed}
  closeObligation(m:MissionState,id:string):void{const o=m.obligations.find(x=>x.id===id);if(!o)return;o.status='closed';o.closedAt=Date.now();syncMissionGates(m);appendLedger(m,'obligation.closed',{payload:{obligation:id}})}
  signature(m:MissionState):string{const data=JSON.stringify({obligations:m.obligations.map(o=>[o.id,o.status]),tasks:m.tasks.map(t=>[t.id,t.status,t.result?.status,t.result?.open_issues,t.result?.needs_context]),workers:m.workers.map(w=>[w.id,w.status,w.model,w.model_variant,w.runtime_recovery_attempt]),evidence:m.evidence.items.map(e=>[e.kind,e.outcome,e.invalidated_at,e.task_id,e.obligation_ids]),files:m.changed_files,blockers:m.blockers,constraints:m.constraints,tasks_constraints:m.tasks.map(t=>[t.id,t.constraints]),gates:m.gates.map(g=>[g.id,g.status,g.reason]),temporary:m.temporary_mutations.map(x=>[x.id,x.status])});let h=2166136261;for(let i=0;i<data.length;i++){h^=data.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
}
