#!/usr/bin/env python3
from pathlib import Path
import glob,hashlib,json,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data/validation/prompt-b-zero-known-defect-loop.json'
HEAD=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
def sha(rel):
    blob=subprocess.check_output(['git','show',f'{HEAD}:{rel}'],cwd=ROOT)
    return hashlib.sha256(blob).hexdigest()
owner_map={
'prompt-b-authority-permission-external-action.json':'Authority/Permission/ExternalAction','prompt-b-cli-developer-tooling-ux.json':'CLI/setup UX','prompt-b-configuration.json':'HiConfig resolver/catalog','prompt-b-context-project-intelligence-compression.json':'Context/PI/Compression','prompt-b-dependency-supply-chain-license.json':'Dependency/release supply chain','prompt-b-evidence-verification-completion.json':'Evidence/Verification/Completion','prompt-b-host-port-portability.json':'HostPort/adapter boundary','prompt-b-human-decision.json':'HumanDecision','prompt-b-install-update-lifecycle.json':'Install/update lifecycle','prompt-b-mission-task-worker.json':'Mission/Task/Worker','prompt-b-persistence-concurrency.json':'Persistence/Concurrency','prompt-b-process-workspace-browser-lifecycle.json':'Process/Workspace/Browser runtime','prompt-b-property-fuzz-testing.json':'Mission persistence validators','prompt-b-security-privacy.json':'Security/privacy boundary','prompt-b-skills-methodology-security.json':'Skill/methodology security','prompt-b-test-suite-audit.json':'Test harness/capability truth','prompt-b-vcs-path-portability.json':'VCS/path portability'}
rows=[];viol=[]
for fp in sorted(glob.glob(str(ROOT/'data/validation/prompt-b-*.json'))):
 p=Path(fp); d=json.loads(p.read_text()); defects=d.get('closed_defects')
 if not defects:continue
 rel=p.relative_to(ROOT).as_posix(); owner=owner_map.get(p.name)
 if not owner:viol.append(f'owner-map-missing:{p.name}');continue
 if d.get('status') not in ('PASS','CLOSED','COMPLETED') and not str(d.get('status','')).startswith('CLOSED_'):viol.append(f'source-receipt-not-closed:{p.name}:{d.get("status")}')
 for x in defects:
  fix=x.get('fix') or x.get('resolution'); did=x.get('id'); cls=x.get('class') or ('HARNESS_OR_VALIDATION_DEFECT' if p.name=='prompt-b-test-suite-audit.json' and did!='mock-runtime-self-promoted-t3' else 'PRODUCT_OR_ARCHITECTURE_DEFECT')
  if not did or not fix:viol.append(f'incomplete-defect-record:{p.name}:{did}');continue
  rows.append({'id':did,'classification':cls,'canonical_owner':owner,'root_cause_record':x.get('finding') or x.get('class') or did,'resolution':fix,'regression_receipt':rel,'regression_receipt_sha256':sha(rel),'closure_pipeline':['discover','classify','canonical-owner','root-cause','fix','regression-test','focused-verification','full-verification','docs-parity','local-commit','ledger','adjacent-reaudit']})
transient=[
 {'id':'startup-health-probe-reentrant-deadlock','classification':'HARDENING_REGRESSION','canonical_owner':'plugin/src/plugin.ts','root_cause_record':'same-server process/workspace health probes were awaited during plugin initialization','resolution':'process/workspace health probes are deferred until plugin initialization returns','proof':'plugin/test/host-capability-contract.test.mjs','anchor':'plugin initialization never waits on same-server process/workspace health probes'},
 {'id':'fresh-consumer-agent-projection-assertion-drift','classification':'ACCEPTANCE_HARNESS_DEFECT','canonical_owner':'scripts/run-fresh-consumer-acceptance.py','root_cause_record':'fresh-consumer assertion depended on a narrower agent response shape than the native endpoint contract','resolution':'acceptance consumes the live agent endpoint and verifies canonical coder projection without invented fields','proof':'data/validation/fresh-consumer-opencode-1.18.18.json','anchor':'coder_agent_observed'},
 {'id':'failure-injection-disk-fixture-not-failing','classification':'TEST_FIXTURE_DEFECT','canonical_owner':'plugin/test/q5-failure-injection.test.mjs','root_cause_record':'initial disk-failure fixture did not force a filesystem write error','resolution':'state root is a regular file so persistence deterministically fails ENOTDIR before any committed state','proof':'plugin/test/q5-failure-injection.test.mjs','anchor':'Q5 injected disk write failure throws synchronously'},
 {'id':'user-journey-authority-test-contract-drift','classification':'TEST_ASSERTION_DRIFT','canonical_owner':'plugin/test/q6-user-journey-acceptance.test.mjs','root_cause_record':'test planted a synthetic hash rather than requesting the canonical exact action contract','resolution':'journey uses requireAuthority and the exact structured authority response','proof':'plugin/test/q6-user-journey-acceptance.test.mjs','anchor':'Q6 authority journey requires exact structured decision'},
 {'id':'user-journey-unsupported-primitive-assumption','classification':'TEST_ASSERTION_DRIFT','canonical_owner':'plugin/test/q6-user-journey-acceptance.test.mjs','root_cause_record':'test confused documented native primitive metadata with a runtime support claim','resolution':'journey asserts UNSUPPORTED/OBSERVED plus forbidden fake behavior rather than requiring primitive metadata to be absent','proof':'plugin/test/q6-user-journey-acceptance.test.mjs','anchor':'Q6 unsupported journey is truthful'},
 {'id':'developer-journey-owner-shape-assumptions','classification':'TEST_ASSERTION_DRIFT','canonical_owner':'plugin/test/q7-developer-journey-acceptance.test.mjs','root_cause_record':'test assumed the methodology catalog top-level shape and bypassed root-to-plugin architecture script indirection','resolution':'journey follows canonical profiles catalog and root npm script to plugin architecture lint owner','proof':'plugin/test/q7-developer-journey-acceptance.test.mjs','anchor':'Q7 contributor adding methodology edits canonical catalog'},
 {'id':'exact-t3-invalid-parent-session-fixture','classification':'ACCEPTANCE_HARNESS_DEFECT','canonical_owner':'section-39 exact-host harness','root_cause_record':'initial workspace child-binding probe used a nonexistent parent session and received native BadRequest','resolution':'fresh exact-host acceptance creates a real parent session before the workspace-bound child','proof':'data/validation/external-opencode-hi-0.1.0-workspace-1.18.18-head-aa9a402.json','anchor':'"child_exact": true'},
 {'id':'npm-view-json-shape-verifier-drift','classification':'RELEASE_VERIFICATION_DEFECT','canonical_owner':'scripts/verify-npm-oidc-release.mjs','root_cause_record':'npm 11 multi-field npm view --json emits dotted field keys while the verifier assumed a nested dist object','resolution':'registry verifier normalizes npm 11 dotted fields and npm 12 array/nested JSON shapes before exact version/integrity/shasum comparison','proof':'plugin/test/r1-npm-oidc-workflow.test.mjs','anchor':"view\['dist\.integrity'\]"},
 {'id':'npm-postpublish-registry-read-after-write-race','classification':'RELEASE_WORKFLOW_DEFECT','canonical_owner':'.github/workflows/npm-publish.yml','root_cause_record':'immediate npm view after a successful publish raced public registry propagation and produced a false-negative E404','resolution':'post-publish registry verification uses a bounded 12-attempt/5-second retry loop and still fails closed if version/digests never converge','proof':'.github/workflows/npm-publish.yml','anchor':'for attempt in $(seq 1 12)'},
 {'id':'npm-packed-public-document-links-incomplete','classification':'RELEASE_PACKAGING_DEFECT','canonical_owner':'scripts/audit-packed-public-docs.py','root_cause_record':'the npm package README linked canonical public documentation that was not guaranteed to be present in the packed artifact','resolution':'all canonical public docs and community targets referenced by README are explicitly packed and a tarball audit rejects missing relative links, stale removed-doc references, or README byte drift','proof':'scripts/audit-packed-public-docs.py','anchor':'broken packed public link'},
 {'id':'windows-packed-doc-audit-npm-shim-resolution','classification':'CI_PORTABILITY_DEFECT','canonical_owner':'scripts/audit-packed-public-docs.py','root_cause_record':'Python subprocess attempted the POSIX npm executable name on Windows where the npm shim is npm.cmd','resolution':'packed documentation audit resolves npm.cmd on Windows and npm on POSIX before invoking npm pack','proof':'scripts/audit-packed-public-docs.py','anchor':"shutil.which('npm.cmd' if os.name=='nt' else 'npm')"},
 {'id':'npm-publish-workflow-missing-python-verification-dependencies','classification':'RELEASE_WORKFLOW_DEFECT','canonical_owner':'.github/workflows/npm-publish.yml','root_cause_record':'v0.1.2 npm publish run 31963900266 failed canonical source verification because requirements-dev.txt was not installed; npm publish did not run','resolution':'npm publish workflow provisions Python 3.11 and installs requirements-dev.txt before canonical source verification; R1 regression asserts both steps','proof':'.github/workflows/npm-publish.yml','anchor':'Install Python verification dependencies'},
 {'id':'post-t4-documentation-stale-publication-state','classification':'DOCUMENTATION_VALIDATION_DEFECT','canonical_owner':'scripts/validate-documentation.py','root_cause_record':'documentation parity did not reject prepublication npm/bootstrap wording after real T4 publication completed','resolution':'current README/installation/release/continuation truth is updated and documentation parity rejects stale npm prepublication wording','proof':'scripts/validate-documentation.py','anchor':'DOC_LOCALIZED_RELEASE_DRIFT'},
]
transient.extend([
 {'id':'short-lived-pty-output-before-attach','classification':'PRODUCT_RUNTIME_DEFECT','canonical_owner':'plugin/src/opencode/open-code-pty-adapter.ts','root_cause_record':'OpenCode PTY create starts immediately while attach is rejected after exit, so a very short process could terminate before Hi established cursor replay and lose user-visible output','resolution':'POSIX requested commands are held behind initial cursor metadata plus a bounded echo-suppressed ready marker; the internal marker is hidden from initial and restart replay before releasing the original command','proof':'plugin/test/p2-opencode-pty-executor.test.mjs','anchor':'P2 POSIX launch barrier waits for initial cursor metadata before releasing the requested command'},
 {'id':'release-certification-stale-phase1-performance-primitives','classification':'VALIDATION_ARCHITECTURE_DRIFT','canonical_owner':'scripts/run-performance-resource-benchmarks.mjs','root_cause_record':'living performance certification still measured removed SkillCatalogIndex, generic Project Intelligence retrieval and ContextGovernor primitives','resolution':'performance certification measures current Phase 2 native skill selection, evidence-backed project methodology learning and bounded Mission runtime projection hot paths','proof':'scripts/run-performance-resource-benchmarks.mjs','anchor':'project_methodology_learning'},
 {'id':'test-harness-stale-fixed-suite-count','classification':'VALIDATION_EVIDENCE_DRIFT','canonical_owner':'scripts/run-test-harness-isolation.py','root_cause_record':'living test-harness acceptance persisted historical full-suite and cwd-probe counts as release truth','resolution':'a canonical harness runner now records fresh terminal counts and zero real-home state delta, while validators require pass==tests and no failures instead of historical totals','proof':'scripts/run-test-harness-isolation.py','anchor':'Counts are terminal observations, never hand-maintained release constants'},
 {'id':'skills-security-stale-second-loader-contract','classification':'VALIDATION_ARCHITECTURE_DRIFT','canonical_owner':'scripts/audit-skills-methodology-security.py','root_cause_record':'living skill-security audit still certified removed SkillCatalogIndex/resource-reader responsibilities after Phase 2 moved actual skill discovery/body/resource loading back to OpenCode','resolution':'skill-security audit now certifies only selected-name confinement, admission/provenance/trust separation, same-name shadow rejection and observed native load while explicitly forbidding a second Hi loader','proof':'scripts/audit-skills-methodology-security.py','anchor':'no_second_skill_catalog_loader'},
 {'id':'native-reevaluation-stale-upstream-source-pin','classification':'VALIDATION_SOURCE_BINDING_DRIFT','canonical_owner':'scripts/audit-opencode-native.py','root_cause_record':'native reevaluation defaulted to an obsolete commit absent from the exact v1.18.18 upstream clone and used a bare git invocation blocked by repository ownership isolation','resolution':'native reevaluation resolves immutable v1.18.18, records the resolved commit, and scopes safe.directory only to its explicit upstream Git command','proof':'scripts/audit-opencode-native.py','anchor':"DEFAULT_COMMIT='v1.18.18'"},
 {'id':'config-validator-stale-second-leaf-count','classification':'VALIDATION_SCHEMA_DRIFT','canonical_owner':'scripts/validate.py','root_cause_record':'a second validator block retained the pre-TeamMode-removal 32-leaf config count after the canonical catalog and primary audit moved to 29 leaves','resolution':'all living config validation now requires the canonical 29-leaf split: 26 runtime, 2 diagnostic and 1 schema marker','proof':'scripts/validate.py','anchor':"{'required':29,'covered':29,'violations':0,'runtime':26,'diagnostic':2,'schema_marker':1}"},
 {'id':'living-audit-stale-proof-anchors','classification':'VALIDATION_PROOF_DRIFT','canonical_owner':'scripts/audit-mission-task-worker.py','root_cause_record':'several living audits retained pre-M15 proof phrases for restart, host ASK authority and browser runtime-resource semantics although the executable tests had evolved','resolution':'mission/persistence/authority/host-port audits now bind the current exact behavioral proof phrases without changing product behavior','proof':'scripts/audit-host-port-portability.py','anchor':'canonical runtime browser-execution resource'},
 {'id':'failure-injection-stale-fixed-targeted-count','classification':'VALIDATION_EVIDENCE_DRIFT','canonical_owner':'scripts/run-failure-injection.py','root_cause_record':'failure-injection acceptance required an obsolete literal 54-test terminal count even though the bounded injection inventory remained 12 and the current targeted suite had grown','resolution':'acceptance now requires a nonempty terminal suite with pass==tests and zero fail/cancelled/skipped/todo while the 12 injection inventory and proof anchors remain exact','proof':'scripts/run-failure-injection.py','anchor':"terminal['pass']==terminal['tests']"},
 {'id':'replay-corpus-stale-completion-reason-class','classification':'VALIDATION_REPLAY_DRIFT','canonical_owner':'data/validation/replay-corpus.json','root_cause_record':'completion owner evolved from generic verification-missing to claim-scoped verification-claims-missing while the deterministic replay corpus retained the obsolete expected reason class','resolution':'replay corpus now matches the canonical claim-linked completion reason without changing runtime behavior','proof':'data/validation/replay-corpus.json','anchor':'verification-claims-missing'},
 {'id':'living-acceptance-hardcoded-source-commit','classification':'VALIDATION_SOURCE_BINDING_DRIFT','canonical_owner':'scripts/validate.py','root_cause_record':'multiple living acceptance validators required obsolete literal source commits while simultaneously requiring current proof hashes','resolution':'living acceptance source binding now verifies exact recorded commit/tree objects and ancestor relation to the current candidate while owner/proof hashes continue to detect material drift','proof':'scripts/validate.py','anchor':'def source_binding_valid(binding)'},
])

for x in transient:
 rel=x['proof']; txt=(ROOT/rel).read_text(errors='replace')
 if x['anchor'] not in txt:viol.append(f'transient-proof-anchor-drift:{x["id"]}')
 rows.append({**{k:v for k,v in x.items() if k not in ('proof','anchor')},'regression_receipt':rel,'regression_receipt_sha256':sha(rel),'closure_pipeline':['discover','classify','canonical-owner','root-cause','fix','regression-test','focused-verification','full-verification','docs-parity','local-commit','ledger','adjacent-reaudit']})
ids=[x['id'] for x in rows]
if len(ids)!=len(set(ids)):viol.append('duplicate-defect-id')
exact=json.loads((ROOT/'data/validation/prompt-b-exact-current-opencode-t3.json').read_text());life=json.loads((ROOT/'data/validation/prompt-b-process-workspace-browser-lifecycle.json').read_text());docs=json.loads((ROOT/'data/validation/documentation-parity.json').read_text())
status='PASS' if not viol and exact.get('status')=='PASS' and life.get('status')=='PASS' and docs.get('status')=='PASS' else 'FAIL'
out={'schema':2,'kind':'PROMPT_B_ZERO_KNOWN_DEFECT_CLOSURE_LOOP','source_checkpoint':{'commit':HEAD},'program':'PROMPT_B','section':40,'status':status,'defects':rows,'summary':{'recorded_findings':len(rows),'unresolved_known_defects':0 if not viol else len(viol),'closure_receipts_checked':len(rows),'documentation_parity_violations':len(docs.get('violations') or []),'exact_t3_capabilities':(exact.get('summary') or {}).get('exact_current_capabilities',0),'lifecycle_invariants_pass':(life.get('summary') or {}).get('covered',0)},'violations':viol,'claim_boundary':'ZERO KNOWN DEFECT means no unresolved defect in the audited Prompt B scope after explicit closure and adjacent evidence re-audit. Full-suite terminal counts belong to fresh final-gates evidence, not this defect ledger; unknown future defects remain possible.'}
OUT.write_text(json.dumps(out,indent=2)+'\n');print(f'zero-known-defect loop {status}: findings={len(rows)} unresolved={out["summary"]["unresolved_known_defects"]}');sys.exit(0 if status=='PASS' else 1)
