import type { HiConfig, ConfigResolutionReport } from '../config/schema.js'
import { MissionStore } from '../runtime/mission/mission-store.js'
import type { AvailableModel } from '../runtime/routing/model-resolver.js'
import { automaticContinuationEnabled, adaptiveIdleEvaluatorEnabled } from '../config/execution-policy.js'
import { inspectProject } from './project-inspection.js'
import type { HostCapabilityView } from '../runtime/host/port.js'
import { configuredPluginSpecs, configuredRemoteInstructions, configuredShareMode, configuredSubagentDepth, providerPolicyView } from '../opencode/native-adapter.js'
import { auditHiToolNamespace } from '../opencode/tool-namespace.js'
import { knownHiCustomRoles } from '../runtime/routing/agent-reuse.js'

export interface DoctorCheck { id:string; status:'pass'|'warn'|'fail'; machine_status?:'pass'|'info'|'action-required'|'not-applicable'; detail:string }
export interface DoctorRuntimeInfo { models?:AvailableModel[]; resolution?:ConfigResolutionReport; capabilities?:HostCapabilityView; hostConfig?:Record<string,unknown>; openCodeVersion?:string; runtimeHostResources?:ReadonlySet<string> }
function providerCount(models:AvailableModel[]):number{return new Set(models.map(m=>m.provider).filter(Boolean)).size}
function hiSpec(x:string):boolean{return x==='opencode-hi'||x.startsWith('opencode-hi@')||/OpenCode-Hi/i.test(x)}

export function runDoctor(config:HiConfig,store:MissionStore,directory?:string,info:DoctorRuntimeInfo={}):DoctorCheck[]{
  const d=directory??process.cwd(),host=info.hostConfig??{},missions=store.all(),stale=missions.filter(m=>m.identity.status==='active'&&Date.now()-m.identity.updated_at>24*60*60*1000).length,pending=missions.reduce((n,m)=>n+m.execution.workers.filter(w=>['created','queued','starting','busy'].includes(w.status)).length,0),stopped=missions.filter(m=>m.continuation.user_interrupted||m.identity.status==='stopped').length
  const project=inspectProject(d),effectiveAgents=(host.agent&&typeof host.agent==='object'?Object.keys(host.agent as Record<string,unknown>):[]),models=info.models??[],providers=providerCount(models),resolution=info.resolution,resolutionStatus=resolution?.canonical===false?'warn':'pass'
  const plugins=configuredPluginSpecs(host),hiPlugins=plugins.filter(hiSpec),localHi=Boolean(project.localHiPlugin),duplicateHi=(project.hiLocalPluginPaths.length+hiPlugins.length)>1,remoteInstructions=configuredRemoteInstructions(host),depth=configuredSubagentDepth(host),providerPolicy=providerPolicyView(host),variantModels=models.filter(m=>(m.variants?.length??0)>0).length,share=configuredShareMode(host),toolAudit=auditHiToolNamespace(['hi_doctor','hi_status','hi_metrics','hi_ledger','hi_readiness','hi_context_artifact_add','hi_context_artifacts','hi_temporary_mutation_register','hi_temporary_mutation_revert','hi_direct_progress','hi_task_start','hi_task_await','hi_task_peek','hi_task_list','hi_task_cancel'])
  const runtimeVersion=info.openCodeVersion??project.openCodeVersion,validatedVersions=config.compatibility.validatedOpenCodeVersions??[],versionValidated=Boolean(runtimeVersion&&validatedVersions.includes(runtimeVersion)),versionKnown=validatedVersions.length>0
  const configuredModelLists=[...Object.entries(config.routing.roleModels).map(([k,v])=>[`role:${k}`,v] as const),...Object.entries(config.routing.categoryModels).map(([k,v])=>[`category:${k}`,v] as const)]
  const inventoryIds=new Set(models.map(m=>m.id));const invalidMappings=models.length?configuredModelLists.filter(([,ids])=>ids.length>0&&!ids.some(id=>inventoryIds.has(id))):[];const primaryDrift=models.length?configuredModelLists.filter(([,ids])=>ids.length>1&&!inventoryIds.has(ids[0])&&ids.slice(1).some(id=>inventoryIds.has(id))):[]
  const c=info.capabilities,hostContracts=c?.contracts??[],processCapability=hostContracts.find(x=>x.id==='process-lifecycle'),workspaceCapability=hostContracts.find(x=>x.id==='workspace-isolation-binding'),browserCapability=hostContracts.find(x=>x.id==='browser-execution')
  const capabilityCounts=hostContracts.reduce((acc,x)=>{acc[x.status]=(acc[x.status]??0)+1;return acc},{} as Record<string,number>)
  const capabilityDetail=(x:typeof processCapability)=>x?`status=${x.status}; verification=${x.verification_level}; runtime-health-required=${x.runtime_health_required===true}; fallback=${x.fallback??'none'}; semantic-loss=${x.semantic_loss.join(' | ')||'none'}; acceptance=${x.acceptance_ref}`:'contract unavailable'
  const nativeDetail=c?`workerRuntime=${c.workerRuntime}; asyncPrompt=${c.asyncPrompt}; abort=${c.abort}; status=${c.sessionStatus}; children=${c.childSessionList}; todo=${c.sessionTodo}; diff=${c.sessionDiff}; fork=${c.sessionFork}; summarize=${c.sessionSummarize}; revert=${c.sessionRevert}; providerInventory=${c.providerInventory}; appLog=${c.appLog}; contracts=${hostContracts.length}; degraded=${c.degraded.join(',')||'none'}`:'capability snapshot unavailable'
  const effectiveObserved=Object.keys(host).length>0
  const effectiveHiPresent=hiPlugins.length>0||localHi
  const projectRegistrationSatisfied=project.pluginRegistered!==false||effectiveHiPresent
  const effectiveRegistrationDrift=effectiveObserved&&!effectiveHiPresent
  const projectSpecs=project.configuredHiPluginSpecs??[]
  const registrationLayerDrift=effectiveObserved&&projectSpecs.length>0&&hiPlugins.length>0&&!projectSpecs.some(spec=>hiPlugins.includes(spec))
  const checks:DoctorCheck[]=[
    {id:'plugin-loaded',status:'pass',detail:'OpenCode-Hi plugin runtime initialized'},
    {id:'config-schema',status:resolutionStatus,detail:`schema=${config.schemaVersion}${resolution?.notes.length?`; ${resolution.notes.join(' | ')}`:''}`},
    {id:'effective-config',status:effectiveObserved?'pass':'warn',detail:effectiveObserved?'OpenCode effective config received through native plugin config hook':'effective config not observed yet; raw project config is not treated as runtime source of truth'},
    {id:'effective-plugin-registration',status:effectiveRegistrationDrift?'fail':effectiveObserved?'pass':'warn',detail:!effectiveObserved?'effective plugin list unavailable':effectiveHiPresent?`Hi present in effective/local runtime surface (${hiPlugins.join(',')||project.hiLocalPluginPaths.join(',')||'local'})`:'Hi runtime initialized but no Hi registration/local plugin is visible in effective config; config layering/registration drift requires reconciliation'},
    {id:'plugin-layer-drift',status:registrationLayerDrift?(project.ownershipState==='healthy'?'fail':'warn'):'pass',detail:registrationLayerDrift?`project Hi spec (${projectSpecs.join(',')}) differs from effective Hi spec (${hiPlugins.join(',')}); a global/managed layer may be shadowing project intent`:`project/effective Hi registration aligned or no project-owned registration to compare`},
    {id:'config',status:'pass',detail:`executionPolicy=${config.executionPolicy}; routing=${config.routing.strategy}; parallel=${config.parallel.enabled}/${config.parallel.max}; compatibility=${config.compatibility.mode}`},
    {id:'project-directory',status:directory?'pass':'warn',detail:d},
    {id:'config-dir',status:'pass',detail:`OPENCODE_CONFIG_DIR=${process.env.OPENCODE_CONFIG_DIR??'host/default'}; project-config=${project.configPath??'none'}`},
    {id:'plugin-registration',status:projectRegistrationSatisfied?'pass':'warn',detail:project.configPath?`config=${project.configPath}; project-registered=${String(project.pluginRegistered)}; effective-hi=${hiPlugins.join(',')||'none'}; local=${localHi}`:`no project OpenCode registration; effective-hi=${hiPlugins.join(',')||'none'}; local=${localHi}`},
    {id:'duplicate-hi-plugin',status:duplicateHi?'fail':'pass',detail:`effective-hi-specs=${hiPlugins.join(',')||'none'}; local-paths=${project.hiLocalPluginPaths.join(',')||'none'}`},
    {id:'tool-namespace',status:toolAudit.ok?'pass':'fail',detail:toolAudit.ok?'Hi custom model-facing tools are hi_* namespaced; no native tool shadowing':`collisions=${toolAudit.collisions.join(',')||'none'}; nonNamespaced=${toolAudit.nonNamespaced.join(',')||'none'}`},
    {id:'opencode-version',status:!runtimeVersion?'warn':versionValidated?'pass':(config.compatibility.mode==='strict'&&versionKnown?'fail':'warn'),detail:!runtimeVersion?'runtime version not exposed; external compatibility smoke must bind exact OpenCode version':versionValidated?`${runtimeVersion} is present in validatedOpenCodeVersions`:versionKnown?`${runtimeVersion} is not in validatedOpenCodeVersions (${validatedVersions.join(',')}); external smoke required`:`${runtimeVersion}; no validated OpenCode version is embedded yet, external smoke required`},
    {id:'subagent-depth',status:depth===undefined?'warn':depth<=1?'pass':'warn',detail:depth===undefined?'host subagent_depth not exposed; Hi child roles deny recursive task delegation independently':`host subagent_depth=${depth}; Hi does not own this global host setting and child roles deny recursive task delegation independently`},
    {id:'experimental-adapter',status:'pass',detail:'experimental.session.compacting is isolated behind ExperimentalOpenCodeAdapter/CompactionBridge boundary'},
    {id:'native-capabilities',status:c?.workerRuntime?'pass':(config.compatibility.mode==='strict'?'fail':'warn'),detail:nativeDetail},
    {id:'host-capability-contracts',status:hostContracts.length?'pass':'warn',detail:hostContracts.length?`contracts=${hostContracts.length}; SUPPORTED=${capabilityCounts.SUPPORTED??0}; DEGRADED=${capabilityCounts.DEGRADED??0}; UNSUPPORTED=${capabilityCounts.UNSUPPORTED??0}; runtime verification remains ${[...new Set(hostContracts.map(x=>x.verification_level))].join(',')}`:'host capability registry unavailable'},
    {id:'process-lifecycle',status:processCapability?.status==='SUPPORTED'?'pass':'warn',detail:capabilityDetail(processCapability)},
    {id:'workspace-isolation-binding',status:workspaceCapability?.status==='SUPPORTED'?'pass':'warn',detail:capabilityDetail(workspaceCapability)},
    {id:'browser-execution',status:browserCapability?.status==='SUPPORTED'&&(!browserCapability.runtime_health_required||info.runtimeHostResources?.has('host-capability:browser-execution'))?'pass':'warn',detail:`${capabilityDetail(browserCapability)}; runtime-available=${Boolean(info.runtimeHostResources?.has('host-capability:browser-execution'))}`},
    {id:'native-session-diff-revert',status:c?.sessionDiff&&c?.sessionRevert?'pass':'warn',detail:c?`diff=${c.sessionDiff}; revert=${c.sessionRevert}; unrevert=${c.sessionUnrevert}; fork=${c.sessionFork}; summarize=${c.sessionSummarize}`:'native session capability snapshot unavailable'},
    {id:'structured-logging',status:c?.appLog?'pass':'warn',detail:c?.appLog?'OpenCode client.app.log available':'structured OpenCode logging unavailable; no custom log framework will be substituted'},
    {id:'permission-surface',status:project.permissionConfigured?'pass':'warn',detail:project.permissionConfigured?`OpenCode permission config detected; skill-specific=${project.skillPermissionConfigured}`:'No explicit OpenCode permission config detected; host defaults apply'},
    {id:'permission-event-runtime',status:'pass',detail:'permission.asked/replied map to WAIT without stagnation increment'},
    {id:'provider-policy',status:'pass',detail:`effective native policy sources=${providerPolicy.source.join(',')||'none'}; allowed=${[...providerPolicy.allowed].join(',')||'unbounded'}; denied=${[...providerPolicy.denied].join(',')||'none'}`},
    {id:'model-inventory',status:models.length>0?'pass':'warn',detail:`${models.length} runtime model(s) across ${providers} provider(s); first 8: ${models.slice(0,8).map((m:any)=>m.id).join(', ')||'none'}`},
    {id:'model-variants',status:models.length===0?'warn':variantModels?'pass':'info' as any,detail:`${variantModels}/${models.length} model(s) expose native variants; Hi chooses a variant only when host inventory exposes it`},
    {id:'model-fallback',status:models.length>0?'pass':'warn',detail:`maxFallbacks=${config.routing.maxFallbacks}; roleOverrides=${Object.keys(config.routing.roleModels).length}; categoryOverrides=${Object.keys(config.routing.categoryModels).length}`},
    {id:'model-mapping-validity',status:models.length===0?'warn':invalidMappings.length?'fail':'pass',detail:models.length===0?'runtime inventory unavailable; configured role/category mappings cannot be validated':invalidMappings.length?`no configured candidate is currently available for ${invalidMappings.map(([k,ids])=>`${k}=[${ids.join(',')}]`).join('; ')}`:`all ${configuredModelLists.length} configured role/category model list(s) have at least one runtime-available candidate`},
    {id:'model-primary-drift',status:models.length===0?'warn':primaryDrift.length?'warn':'pass',detail:models.length===0?'runtime inventory unavailable; primary drift cannot be evaluated':primaryDrift.length?`configured primary unavailable but fallback remains usable for ${primaryDrift.map(([k,ids])=>`${k}: primary=${ids[0]} fallback=${ids.slice(1).find(id=>inventoryIds.has(id))}`).join('; ')}`:'configured primary candidates are runtime-available or no ordered fallback drift exists'},
    {id:'routing-config',status:project.routingConfigPath===undefined?'info':(project.routingConfigSchemaValid?'pass':'warn'),detail:project.routingConfigPath===undefined?'no .opencode/hi/policy/routing.json; per-role mapping uses scoring fallback':`path=${project.routingConfigPath}; schema=${project.routingConfigSchema}; strategy=${project.routingConfigStrategy}; roles=${Object.keys(project.routingConfigRoleModels??{}).join(',')||'none'}; Hi merged into HiConfig.routing`},
    {id:'agent-definitions',status:effectiveAgents.length||project.agentDefinitions.length?'pass':'warn',detail:(effectiveAgents.length||project.agentDefinitions.length)?`${new Set([...effectiveAgents,...project.agentDefinitions]).size} effective/project agent definition(s): ${[...new Set([...effectiveAgents,...project.agentDefinitions])].slice(0,8).join(',')}`:'No Hi/effective agent definitions detected'},
    {id:'built-in-agent-reuse-policy',status:'pass',detail:`No generic agent framework; ${knownHiCustomRoles().length} Hi roles are retained only for explicit Hi permission/result/evidence contracts. Unknown/equivalent capabilities prefer native OpenCode agents.`},
    {id:'skill-discovery',status:project.discoveredSkills.length?'pass':'warn',detail:project.discoveredSkills.length?`${project.discoveredSkills.length} discovered project/global skill(s); packaged Hi-native skills are registered separately`:'No project/global SKILL.md roots detected; packaged Hi-native skills remain available'},
    {id:'orchestration-ownership',status:'pass',detail:'Hi-native skills are methodology-only; child Hi control-plane tools and recursive task dispatch remain denied'},
    {id:'remote-instructions',status:remoteInstructions.length?'warn':'pass',detail:remoteInstructions.length?`remote instructions present and require trust review: ${remoteInstructions.slice(0,5).join(', ')}`:'no remote instruction URL in effective config'},
    {id:'session-sharing',status:share&&String(share).toLowerCase()!=='manual'?'warn':'pass',detail:`share=${share===undefined?'host/default':JSON.stringify(share)}; Hi never auto-shares mission/ledger data`},
    {id:'mission-store',status:stale?'warn':'pass',detail:`${missions.length} mission(s); ${stale} stale active; ${pending} pending worker; ${stopped} user-stopped; permission-waits=${missions.reduce((n,m)=>n+(m.authority.pending_permissions??0),0)}`},
    {id:'runtime-state',status:project.runtimeState==='invalid'?'fail':project.runtimeState==='missing'?'warn':'pass',detail:`${project.runtimeState}${project.runtimeSchema?`; schema=${project.runtimeSchema}`:''}${project.runtimeSchemaValid===false?'; current-only-schema-required=true':''}`},
    {id:'ownership-state',status:project.ownershipState==='invalid'||project.configDrift===true?'fail':project.ownershipState==='missing'?'warn':'pass',detail:`${project.ownershipState}${project.ownershipSchema?`; schema=${project.ownershipSchema}`:''}${project.configDrift!==undefined?`; configDrift=${project.configDrift}`:''}`},
    {id:'interrupted-transaction',status:project.interruptedTransaction?'fail':'pass',detail:project.interruptedTransaction?'lifecycle transaction journal present; run recover':'none'},
    {id:'completion-owner',status:'pass',detail:'runtime-owned completion, required evidence kinds and freshness enabled'},
    {id:'user-interrupt-guard',status:'pass',detail:'continuation dispatcher rejects stopped/user-interrupted missions; only a new user message can resume'},
    {id:'continuation-controller',status:config.executionPolicy==='manual'?'info':'pass',detail:`mode=${config.executionPolicy}; child-wake=${automaticContinuationEnabled(config.executionPolicy)?'automatic':'manual'}; idle-evaluator=${adaptiveIdleEvaluatorEnabled(config.executionPolicy)?'adaptive':'disabled'}`},
  ]
  for(const warning of project.warnings)checks.push({id:'project-warning',status:'warn',detail:warning})
  for(const check of checks)if(!check.machine_status)check.machine_status=check.status==='pass'?'pass':check.status==='fail'?'action-required':'info'
  return checks
}
export function formatDoctor(c:DoctorCheck[]):string{return c.map(x=>`${(x.machine_status??x.status).toUpperCase()} ${x.id}: ${x.detail}`).join('\n')}
