import type { MissionState } from '../mission/types.js'
import { TaskRuntime } from '../task/task-runtime.js'
import { appendLedger } from '../ledger/ledger.js'
export interface TeamMessage{id:string;at:number;from:string;to:string;text:string;dedupe_key?:string;delivered_to:string[];processed_by:string[];reservations:Record<string,{reserved_at:number;expires_at:number}>}
export interface TeamBoardItem{id:string;title:string;owner?:string;status:'open'|'in-progress'|'done'|'blocked';evidence?:string[];updated_at:number}
export interface TeamState{id:string;mission_id:string;mission_generation:number;objective:string;status:'active'|'shutdown';shutdown_reason?:string;members:string[];worker_ids:string[];member_workers:Record<string,string>;messages:TeamMessage[];board:TeamBoardItem[];created_at:number;expires_at:number;turn_count:number}
export interface TeamLimits{maxMembers:number;maxMessages:number;maxWallMs:number;maxTurns:number}
function uid(p:string){return`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
export class TeamRuntime{
  #teams=new Map<string,TeamState>();constructor(private tasks:TaskRuntime,private enabled:()=>boolean,private limits:()=>TeamLimits){}
  get(id:string){return this.#teams.get(id)}
  list(missionID:string){return[...this.#teams.values()].filter(t=>t.mission_id===missionID)}
  private active(teamID:string):TeamState{const t=this.#teams.get(teamID);if(!t||t.status!=='active')throw new Error('Active team not found');if(Date.now()>=t.expires_at)throw new Error('Team wall-time expired; parent must shutdown/reconcile team');return t}
  private assertCurrentMission(m:MissionState,t:TeamState):void{if(t.mission_id!==m.mission_id||t.mission_generation!==m.generation)throw new Error('Stale team generation; shutdown/reconcile the old team before continuing')}
  private async startMember(m:MissionState,t:TeamState,role:string,overrideModel?:string,overrideVariant?:string):Promise<string>{const readOnly=new Set(['architect','repository-explorer','qa-reviewer','security-reviewer','visual-qa']).has(role),started=await this.tasks.start(m,{objective:`${t.objective}\nTeam perspective: ${role}. Report findings to parent; do not create another team.`,role,category:m.risk==='high'?'critical':'deep',scope:readOnly?[]:m.intent.likelyTargets,constraints:['parent-mediated team','no nested team','bounded scope','compact evidence'],model:overrideModel,modelVariant:overrideVariant});t.worker_ids.push(started.worker_id);t.member_workers[role]=started.worker_id;return started.worker_id}
  async create(m:MissionState,objective:string,members:string[],memberModels?:Record<string,{model?:string;variant?:string}>):Promise<TeamState>{if(!this.enabled())throw new Error('Team Mode disabled');if(this.list(m.mission_id).some(t=>t.status==='active'))throw new Error('Nested or second active team is not allowed');const l=this.limits(),unique=[...new Set(members.map(x=>x.trim()).filter(Boolean))].slice(0,l.maxMembers);if(unique.length<2)throw new Error('Team Mode requires at least two distinct members');const now=Date.now(),team:TeamState={id:uid('team'),mission_id:m.mission_id,mission_generation:m.generation,objective,status:'active',members:unique,worker_ids:[],member_workers:{},messages:[],board:[],created_at:now,expires_at:now+l.maxWallMs,turn_count:0};this.#teams.set(team.id,team);m.execution_mode='team';appendLedger(m,'team.created',{payload:{team_id:team.id,members:unique,expires_at:team.expires_at,member_models:memberModels?Object.keys(memberModels).length:0}});try{for(const role of unique){const override=memberModels?.[role];await this.startMember(m,team,role,override?.model,override?.variant)}return team}catch(error){for(const worker of [...team.worker_ids])try{await this.tasks.cancel(m,worker)}catch{}this.#teams.delete(team.id);m.execution_mode='single';appendLedger(m,'team.create.rolled-back',{payload:{team_id:team.id,error:String(error)}});throw error}}
  async addMember(m:MissionState,teamID:string,role:string,overrideModel?:string,overrideVariant?:string):Promise<{member:string;worker_id:string}>{const t=this.active(teamID);this.assertCurrentMission(m,t);const clean=role.trim();if(!clean)throw new Error('Member role required');if(t.members.includes(clean))throw new Error('Member already exists');if(t.members.length>=this.limits().maxMembers)throw new Error('Team member limit reached');t.members.push(clean);try{const worker_id=await this.startMember(m,t,clean,overrideModel,overrideVariant);appendLedger(m,'team.member.added',{worker_id,payload:{team_id:teamID,member:clean}});return{member:clean,worker_id}}catch(e){t.members=t.members.filter(x=>x!==clean);delete t.member_workers[clean];throw e}}
  async removeMember(m:MissionState,teamID:string,role:string):Promise<boolean>{const t=this.active(teamID);this.assertCurrentMission(m,t);if(!t.members.includes(role))return false;if(t.members.length<=2)throw new Error('Team Mode requires at least two members; shutdown the team instead');const worker=t.member_workers[role];if(worker)await this.tasks.cancel(m,worker);t.members=t.members.filter(x=>x!==role);delete t.member_workers[role];t.worker_ids=t.worker_ids.filter(x=>x!==worker);appendLedger(m,'team.member.removed',{worker_id:worker,payload:{team_id:teamID,member:role}});return true}
  message(m:MissionState,teamID:string,from:string,to:string,text:string,dedupeKey?:string):TeamMessage{const t=this.active(teamID);this.assertCurrentMission(m,t);if((from!=='parent'&&!t.members.includes(from))||(!t.members.includes(to)&&to!=='parent'&&to!=='all'))throw new Error('Unknown team member');const l=this.limits(),key=dedupeKey?.trim();if(key){const prior=t.messages.find(x=>x.dedupe_key===key&&x.from===from&&x.to===to);if(prior){appendLedger(m,'team.message.duplicate-ignored',{payload:{team_id:teamID,message_id:prior.id,from,to,dedupe_key:key}});return prior}}if(t.messages.length>=l.maxMessages)throw new Error('Team mailbox limit reached');if(t.turn_count>=l.maxTurns)throw new Error('Team turn limit reached');const msg:TeamMessage={id:uid('msg'),at:Date.now(),from,to,text:text.slice(0,2000),dedupe_key:key||undefined,delivered_to:[],processed_by:[],reservations:{}};t.messages.push(msg);t.turn_count++;appendLedger(m,'team.message',{payload:{team_id:teamID,from,to,turn:t.turn_count}});return msg}
  inbox(teamID:string,member:string,since?:number,limit=12,replay=false):TeamMessage[]{const t=this.active(teamID);if(member!=='parent'&&!t.members.includes(member))throw new Error('Unknown team member');const now=Date.now(),after=Number.isFinite(since)?Number(since):0,cap=Math.max(1,Math.min(24,Math.floor(limit))),ttl=120000;for(const msg of t.messages){const r=msg.reservations?.[member];if(r&&r.expires_at<=now&&!msg.processed_by?.includes(member))delete msg.reservations[member]}const eligible=t.messages.filter(x=>x.at>after&&(x.to===member||x.to==='all')&&!x.processed_by?.includes(member)&&(replay||!x.reservations?.[member])).slice(0,cap);if(!replay)for(const msg of eligible){msg.reservations??={};msg.reservations[member]={reserved_at:now,expires_at:now+ttl};msg.delivered_to=[...new Set([...(msg.delivered_to??[]),member])]}return eligible}
  messageAck(m:MissionState,teamID:string,member:string,messageID:string,processed=true):boolean{const t=this.active(teamID);if(member!=='parent'&&!t.members.includes(member))throw new Error('Unknown team member');const msg=t.messages.find(x=>x.id===messageID);if(!msg)return false;msg.reservations??={};msg.processed_by??=[];if(processed){msg.processed_by=[...new Set([...msg.processed_by,member])];delete msg.reservations[member];appendLedger(m,'team.message.processed',{payload:{team_id:teamID,message_id:messageID,member}})}else{delete msg.reservations[member];appendLedger(m,'team.message.released',{payload:{team_id:teamID,message_id:messageID,member}})}return true}
  boardUpsert(m:MissionState,teamID:string,input:{id?:string;title:string;owner?:string;status?:TeamBoardItem['status'];evidence?:string[]}):TeamBoardItem{const t=this.active(teamID);this.assertCurrentMission(m,t);if(input.owner&&!t.members.includes(input.owner))throw new Error('Unknown board owner');let item=input.id?t.board.find(x=>x.id===input.id):undefined;const now=Date.now();if(!item){item={id:uid('tb'),title:input.title.slice(0,500),owner:input.owner,status:input.status??'open',evidence:input.evidence?.slice(0,8),updated_at:now};t.board.push(item)}else{item.title=input.title.slice(0,500);item.owner=input.owner??item.owner;item.status=input.status??item.status;item.evidence=input.evidence?.slice(0,8)??item.evidence;item.updated_at=now}appendLedger(m,'team.board.updated',{payload:{team_id:teamID,item_id:item.id,status:item.status,owner:item.owner}});return item}
  async shutdown(m:MissionState,teamID:string,reason='explicit'):Promise<boolean>{const t=this.#teams.get(teamID);if(!t)return false;if(t.status==='shutdown')return true;t.status='shutdown';t.shutdown_reason=reason;const workers=[...t.worker_ids];t.worker_ids=[];t.member_workers={};if(m.mission_id===t.mission_id&&m.execution_mode==='team')m.execution_mode='single';appendLedger(m,reason==='expired'?'team.expired':'team.shutdown',{payload:{team_id:teamID,reason,workers:workers.length}});for(const worker of workers)try{await this.tasks.cancel(m,worker)}catch(error){appendLedger(m,'team.member.cancel.failed',{worker_id:worker,payload:{team_id:teamID,reason,error:String(error)}})}return true}
  async expireMission(m:MissionState,now=Date.now()):Promise<void>{for(const t of this.list(m.mission_id))if(t.status==='active'&&(t.mission_generation!==m.generation||now>=t.expires_at))await this.shutdown(m,t.id,t.mission_generation!==m.generation?'stale-generation':'expired')}
  async reconcileMission(m:MissionState):Promise<void>{for(const t of this.list(m.mission_id)){if(t.status!=='active')continue;if(t.mission_generation!==m.generation){await this.shutdown(m,t.id,'stale-generation');continue}const activeWorkers=t.worker_ids.map(id=>m.workers.find(w=>w.id===id)).filter(Boolean).filter((w:any)=>!['completed','failed','cancelled'].includes(w.status));if(activeWorkers.length>=2)continue;if(activeWorkers.length===0){await this.shutdown(m,t.id,'members-terminal');continue}const remaining=activeWorkers.map((w:any)=>w.id);t.status='shutdown';t.shutdown_reason='insufficient-active-members';t.worker_ids=[];t.member_workers={};if(m.execution_mode==='team')m.execution_mode='single';appendLedger(m,'team.degraded',{payload:{team_id:t.id,reason:'insufficient-active-members',remaining_workers:remaining}})}}
  async shutdownMission(m:MissionState):Promise<void>{for(const t of this.list(m.mission_id))if(t.status==='active')await this.shutdown(m,t.id)}
}
